### ISSUE TITLE
[Bug]: Can not import Transactions from CSV into a new created Account since #24.8.0

### ISSUE THREAD

**Issue by solarding** [actualbudget/actual#3211] opened 2024-08-06 19:13 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

A bug happened!

I just updated to the new version, and I created a new account.
In this new Account I could not import the exported CSV transactions anymore. If i switch to an older existed account, the Import tool just show me the transactions with the same CSV.
Anyone experiencing the same problem? Or do i miss somehing? 

I reverted back to ver 24.7 , now the Import works again.  
BTW:  another problem is 24.8 installation does not create a startup menu link in C:\Users\user1\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 11

**Comment by solarding** [comment] 2024-08-06 19:14
Please let me know if you can not reproduce the problem. I will see what I can help with the steps to reproduce it

**Comment by MatissJanis** [comment] 2024-08-06 19:33
Please provide reproduction steps (this includes a export budget file + a sample CSV)

**Comment by solarding** [comment] 2024-08-06 19:56
[1027083060.csv](https://github.com/user-attachments/files/16515081/1027083060.csv)
[2024-08-06-My Finances.zip](https://github.com/user-attachments/files/16515082/2024-08-06-My.Finances.zip)
Here you are. thanks!

**Comment by solarding** [comment] 2024-08-06 19:57
Here you are, thanks !
[2024-08-06-My Finances.zip](https://github.com/user-attachments/files/16515097/2024-08-06-My.Finances.zip)
[1027083060.csv](https://github.com/user-attachments/files/16515098/1027083060.csv)

**Comment by MatissJanis** [comment] 2024-08-07 19:23
What steps should I take to reproduce the issue?

Seemed to work just fine for me.

<img width="1439" alt="Screenshot 2024-08-07 at 20 22 24" src="https://github.com/user-attachments/assets/f5662f57-d115-4274-baec-f15a1214b613">
<img width="1440" alt="Screenshot 2024-08-07 at 20 22 42" src="https://github.com/user-attachments/assets/dfec8701-d67e-45ed-8a98-a7a383a9718c">

**Comment by psybers** [comment] 2024-08-11 00:39
@MatissJanis As mentioned in #3227 (dupe of this one):

Caused by this commit: https://github.com/actualbudget/actual/commit/30a70f56270d22577c1f2e3d99a3113e8219a28d

**Comment by pmoon00** [comment] 2024-08-11 04:30
@MatissJanis happy to look into this. Had a look at the error provided in #3227 but it's not super obvious how this change brought about this error. Will look into it more, but do you have any findings to share yourself @MatissJanis?

**Comment by pmoon00** [comment] 2024-08-11 04:43
Just double checking that this is the error you are reporting @solarding 

![image](https://github.com/user-attachments/assets/49b0d4f6-0ea7-4894-9725-ce837fbf2d01)

**Comment by psybers** [comment] 2024-08-11 04:48
@pmoon00 That wasn't the error I was seeing (as reported in #3227).

**Comment by pmoon00** [comment] 2024-08-11 04:49
> @pmoon00 That wasn't the error I was seeing (as reported in #3227).

I understand this is a different error to what you reported in #3227. Right now I'm trying to figure out if this issue is reporting something that is the same what you report or if it's two different issues.

**Comment by pmoon00** [comment] 2024-08-11 07:48
@psybers I believe the issue described here is unrelated to the issue you are referring to #3227.

**Comment by eireksten** [comment] 2024-08-11 14:12
Briefly checked, since I got this problem when creating a budget. To me it looks like it would happen on all new accounts, when trying to import csv.

From what I could tell, the missing `csv-mappings-${accountId}` causes a crash in `getInitialMappings` due to the `trx_id` and `selected` fields not being strings. Thus calling `match` on them fails.

![image](https://github.com/user-attachments/assets/a4d4d264-32c8-46ef-bcfc-d7ce296db637)

**Comment by youngcw** [comment] 2024-08-11 20:03
Can this be closed now that #3232 is merged?

**Comment by MatissJanis** [comment] 2024-08-11 20:06
No. #3232 doesn't fix this issue.

See reproduction steps here: https://github.com/actualbudget/actual/issues/3211#issuecomment-2274196124

**Comment by pmoon00** [comment] 2024-08-11 20:06
> Can this be closed now that #3232 is merged?

I don't think so, I don't think the two issues are related.

**Comment by MikesGlitch** [comment] 2024-08-14 09:50
Closed by: #3251

**Closed by MikesGlitch** 2024-08-14 09:50 UTC
Labels: bug, good first issue, help wanted, transaction import
