### ISSUE TITLE
[Bug]: "There was an internal error" when syncing a specific account

### ISSUE THREAD

**Issue by Arnoud-B** [actualbudget/actual#3966] opened 2024-12-12 09:31 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

For over a month now I get a "There was an internal error" message when syncing a specific account. Even when I recreate the account + sync, I still get the error. Is this a GoCardless issue or an Actual Budget issue?

Exact error message:
![CleanShot 2024-12-12 at 10 18 18@2x](https://github.com/user-attachments/assets/9fc296ee-5e0b-400f-b36f-292abb4cd60d)

Console logs:
![CleanShot 2024-12-12 at 10 16 37@2x](https://github.com/user-attachments/assets/f6a08927-959d-4497-b97b-cf31f6f66947)
![CleanShot 2024-12-12 at 10 18 51@2x](https://github.com/user-attachments/assets/4afec1c7-2455-428e-9610-d37b2945b456)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Safari

### Operating System

Mac OSX

**Comment by MMichotte** [comment] 2024-12-24 11:13
Same issue here but slightly different error message:
<img width="411" alt="Screenshot 2024-12-24 at 12 08 25" src="https://github.com/user-attachments/assets/c0c6c919-2cee-4866-bcf4-88df4edba078" />

**Comment by youngcw** [comment] 2024-12-24 17:29
If you have not reached out on discord for this already please do.  We try to keep all bank sync support over there.  Ill close this for now, but if you are able to track down a specific bug then you can reopen this or open a new ticket.

**Closed by youngcw** 2024-12-24 17:29 UTC
Labels: bug

**Comment by Arnoud-B** [comment] 2024-12-27 10:49
@MMichotte Thanks for sharing your error log as well. I noticed something different in there that I suspected was related to my issue as well:
`Error: payeeName is required`
I remembered I have a recurring transaction set up with a schedule where the payee name is automatically removed each time for some reason. So I searched for this transaction, updated the payee name so it wouldn't be empty, and voila: the error did not occur again!

@youngcw I hadn't reached out on Discord because it seemed I needed an invitation first.

**Comment by MMichotte** [comment] 2024-12-30 13:25
I found the culprit in my case.
One transaction does indeed not contain a payeeName. The issue is that it directly comes like that from my bank so I have no way of changing that.

If I recall correctly, it originated from a generated multi-QR code to quickly be reimbursed by multiple friends. Other one-to-one QR codes seem to work properly though. 

```json
{
    "transactionId": "2024-12-09-08.38.45.738194",
    "bookingDate": "2024-12-09",
    "valueDate": "2024-12-09",
    "transactionAmount": {
        "amount": "9.00",
        "currency": "EUR"
    },
    "creditorName": "XXXXX MARTIN",
    "creditorAccount": {
        "iban": "BE0000000005970",
        "currency": "EUR"
    },
    "remittanceInformationStructured": "66640124341147062103XXXXXX680341140",
    "bankTransactionCode": "PMNT-MCRD-POSP",
    "proprietaryBankTransactionCode": "0450000",
    "internalTransactionId": "356c753577b9683b24d211f1fe4676f0",
    "date": "2024-12-09",
    "booked": true
}
``` 
<img width="1176" alt="Screenshot 2024-12-30 at 14 12 46" src="https://github.com/user-attachments/assets/ff786bd3-76b1-43a0-b5a7-c4059a51eafd" />

I am not sure on how this could be solved at its root so maybe we should handle this exception in the goCardless connector ? 
Adding an "unknown" payeeName by default (or blank "" ?)  for example ? 
@youngcw what do you think about this ?

**Comment by matt-fidd** [comment] 2024-12-30 13:56
Looks like an issue in the custom bank handler https://github.com/actualbudget/actual-server/blob/2ef397112cc1f189fd813677b5b2e1d61976c985/src/app-gocardless/banks/FORTUNEO_FTNOFRP1XXX.js

**Comment by youngcw** [comment] 2024-12-30 15:58
@MMichotte you should open a new issue for that

**Comment by robxgd** [comment] 2025-01-03 00:56
@MMichotte I am having the same issue. logged the official issue here: #4078
