### ISSUE TITLE
Filtering a category's transactions doesn't update the total

### ISSUE THREAD

**Issue by Deguello** [actualbudget/actual#296] opened 2022-03-27 23:24 UTC
1. Click the Spent column on a category.

2. The sum of the transactions in the resulting register view matches the category total, as expected.

3. Apply a filter that excludes one or more of the listed transactions.

4. The transactions which don't match the filter disappear, as expected.

5. The category total at the top left of the screen doesn't update to reflect the actual total of the remaining transactions (it still reflects the category total).

I expect the displayed total to update to reflect the sum of the displayed transactions rather than staying the same as the category total.

**Comment by carkom** [comment] 2023-11-08 11:15
I agree with @Kidglove57, this is by design. The label at the top shows: "Food (August 2023)", for example. Applying filters does not change the "total cleared" for that category in that month, it changes the transactions listed. You can select all transactions to see a "total selected box" as a functioning work around for your use case.

Are we happy to close this one?

**Comment by Kidglove57** [comment] 2023-11-08 11:52
Thanks @carkom. Yes, I would agree that this should be closed.
However, the separate issue of Splits not calculating correctly in filters remains.

**Comment by carkom** [comment] 2023-11-08 14:27
Does #1864 fix that concern?

**Comment by Kidglove57** [comment] 2023-11-08 15:14
Yes- thank you for drawing that to my attention. It certainly does!

**Closed** 2023-11-11 23:01 UTC
Labels: needs testing
