### ISSUE TITLE
Real data overwritten if you view demo

### ISSUE THREAD

**Issue by Hennessy811** [actualbudget/actual#22] opened 2022-05-02 11:25 UTC
Just encountered this issue - created file, filled with the data - schedules, budget, etc, all good

Then decided to check out the demo to see what else can I bring - so when I logged back in my file - all data is from the demo!

It suggested to reset the sync and repair, but no luck, data is lost!

**Comment by jlongster** [comment] 2022-05-03 03:42
Yes I'm SO sorry, this is the same as https://github.com/actualbudget/actual-server/issues/23

There's a bad misconfiguration forcing it to go on a SUPER unreliable code path (it needs `SharedArrayBuffer`). So sorry if you lost data :(

**Comment by rich-howell** [comment] 2022-08-20 10:56
Closing this issue as it is a duplicate of [this issue](https://github.com/actualbudget/actual-server/issues/23) thanks for reporting @Hennessy811

**Closed by rich-howell** 2022-08-20 10:56 UTC
Labels: bug
