### ISSUE TITLE
[Feedback] Electron/Desktop App

### ISSUE THREAD

**Issue by Shazib** [actualbudget/actual#1047] opened 2023-05-18 23:48 UTC
Experimental builds of the Electron-based desktop app are now available with every change we make to Actual. Go to [this GitHub Actions page](https://github.com/actualbudget/actual/actions/workflows/electron-master.yml?query=branch%3Amaster+event%3Apush), click on the top entry, make sure you’re logged into GitHub, and then click on the link for your platform under “Artifacts.” Make sure to read the below warnings before proceeding.

Known issues/warnings:

- The Electron app has more permissions than the web client by virtue of being a desktop app. While we will do our best to avoid bugs that affect your wider system, make sure you have a good backup system set up on your computer before using the desktop app.
- The app binaries are currently not code signed, so you may need to bypass your operating system’s security warnings in order to get the app to run. Don’t trust random strangers on the internet who tell you to do this! If you build and run the Electron app locally instead of using the pre-built artifact downloads you won’t have to override security settings.
- There are not yet official/stable releases of the desktop app, and it will not auto-update.
- If you want to use both the web and Electron clients, we recommend using the `:edge` version of the server to ensure both clients are at the very bleeding edge. If you don’t do this, you may run into “out-of-sync migrations” errors on the web client.

We hope to clean up all of these loose ends (along with any bugs you identify) before making a stable release of the Electron app. In the future, we will do our best to release Electron app updates at the same time as all other package updates.

_[added by maintainers]_

----

Opening this issue to record issues and to-do items for the electron app.

Issues
- [x] Side-Nav broken (reported by Matiss)
- [x] Crashes when clicking 'Rules' (maybe not an issue?? can't reproduce)
- [x] Middle click on sidebar opens empty windows.
- [x] Opening Reports page results in two network-failure events
- [x] 'Learn More' in settings doesn't work
- [x] 'Release Notes' in settings doesn't work
- [x] 'Find schedules' blanks out page behind it while modal is opened from menu bar
- [x] 'Repair Split Transaction' in 'Tools' menu doesn't do anything?
- [x] Create Backup/Load from Backup broken
- [x] Broken sockets when reloading
- [x] Fix the 'find schedules' menu option.
- [ ] Check anywhere new/malloc may be allocating memory outside the v8 sandbox. See #1238 
- [ ] Add the 'fix split transactions' menu item back in?

macOS Issues (Help Needed)
- [x] Top of sidebar [overlaps](https://github.com/actualbudget/actual/assets/25517624/d2076aaf-dc83-4f39-aaf5-b6ed69d38908) with window controls on macOS
- [x] [Jank](https://github.com/actualbudget/actual/assets/25517624/2fde9c41-0abd-4f65-b662-2bf732e34260) when mousing between area under hidden titlebar/toolbar and window content area on macOS

To Test
- [x] Nordigen integration (only works with a server)
- [ ] Goal Templates
- [x] All basic functionality...?
- [ ] Tester needed for Linux and OS X
- [x] ~~Electron Auto-Updater?~~

Future Items
- [x] ~~Investigate codesigning/deploying to Mac/Windows/Linux stores~~
- [x] ~~Add releases to Github...~~

![image](https://github.com/actualbudget/actual/assets/4405777/8487d0c4-5519-489d-82dc-815f794867c5)

**Comment by rich-howell** [comment] 2023-05-19 06:42
I am downloading Ubuntu, will spin it up in Hyper-V this evening and give this a shot 

Windows version is pretty tight, couldn't find any immediate issues other than the ones highlighted.

**Comment by youngcw** [comment] 2023-05-26 16:28
I cant connect to my server via reverse proxy because the cert isn't known (my best guess).  In a browser I just have to click the proceed button, but there isn't an option to do that in the ubuntu app.

If I use an IP address it works fine even with just http.

**Comment by youngcw** [comment] 2023-05-26 16:33
Goal templates seem to be working fine.

**Comment by Shazib** [comment] 2023-05-26 19:42
> I cant connect to my server via reverse proxy because the cert isn't known (my best guess).  In a browser I just have to click the proceed button, but there isn't an option to do that in the ubuntu app.
> 
> 
> 
> If I use an IP address it works fine if I use http.

Yeah I'm trying to see if I can get node to pop up some kind of 'accept certificate' message or something (fire some callback) but haven't cracked it as yet. Electron has a function for it but the issue is in the backend not electron.

**Comment by MatissJanis** [comment] 2023-06-02 18:44
[bug report]
The build artefactor for macosx does not seem to work. I think websockets are not running?

```
in.4a5f855a.js:2 WebSocket connection to 'ws://localhost:64796/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

Repro:
1. download the artefact here https://github.com/actualbudget/actual/actions/runs/5148653600
2. install it
3. launch it
4. observe a never ending loading spinner

What's weird is.. sometimes the app works. Other times it does not and it is just stuck.

**Comment by Shazib** [comment] 2023-06-02 19:27
> [bug report]
> 
> The build artefact for macosx does not seem to work. I think websockets are not running?
> 
> 
> 
> ```
> 
> in.4a5f855a.js:2 WebSocket connection to 'ws://localhost:64796/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
> 
> ```
> 
> 
> 
> Repro:
> 
> 1. download the artefact here https://github.com/actualbudget/actual/actions/runs/5148653600
> 
> 2. install it
> 
> 3. launch it
> 
> 4. observe a never ending loading spinner
> 
> 
> 
> What's weird is.. sometimes the app works. Other times it does not and it is just stuck.

Unfortunately I don't have a Mac to test but one thing that comes to mind with this being intermittent is that perhaps the port it's choosing for the socket is not actually free (or reserved etc)?

**Comment by MatissJanis** [comment] 2023-06-02 20:33
(I might be wrong)

Could the problem be that multiple sockets get opened up? I am able to reliably reproduce if I open up the app and then do "cmd+r" (refresh).

--

One more bug: it's not possible to connect it to a remote server. I think the child process does not have network access.

```
FetchError: request to https://xxxxxxxxx/info failed, reason: connect ENETUNREACH
```

**Comment by Shazib** [comment] 2023-06-03 00:39
Yep! The front/client end does reconnect on a Ctrl+R, and fails. The ws server keeps running so it _should_ just close the client connection and open a new one on the same port.

**Comment by MatissJanis** [comment] 2023-06-04 19:45
Update on `ENETUNREACH` issue: my network does not have ipv6. However, node-fetch was for some reason trying to use it.. thus it was blowing up. Very strange.. but explicitly turning off ipv6 in my local network settings seems to have fixed the problem for me.

**Comment by Shazib** [comment] 2023-06-04 20:19
Do we need to implement something in-app to cope with this? i.e. fallback to ipv4 if 6 fails or something?

**Comment by MatissJanis** [comment] 2023-06-04 20:21
> Do we need to implement something in-app to cope with this? i.e. fallback to ipv4 if 6 fails or something?

This might just be with weird network configuration. So I would recommend NOT doing anything for now. And to wait and see if others run into the same problem.

**Comment by TomAFrench** [comment] 2023-06-28 16:50
Thanks for working on this @Shazib. I much prefer to use the desktop app and really struggled to get it building in CI so glad to see it working again.

**Comment by Shazib** [comment] 2023-06-29 21:33
Creating/Loading backuos & Rules seem to be pretty solid, so i've gona ahead and marked them off on here.

**Comment by MatissJanis** [comment] 2023-07-29 11:10
Just finished testing the electron app again. Very exciting to see all the progress! I think we'll be able to start doing official beta releases for it very soon to get some more feedback.

Some bugs spotted (all on mac os):

- [ ] the minimize/maximize osx icons overlay the budget name (possibly missing some top padding? or maybe a toggle to turn on top-bar?)

<img width="252" alt="Screenshot 2023-07-29 at 12 03 22" src="https://github.com/actualbudget/actual/assets/886567/ca08bd58-c726-4dc1-bf65-49a52e4e06ef">

- [ ] when you collapse the side-nav - it's very difficult to bring it back open (very likely the same root cause same as the report above)
- [ ] export data is not working
- [ ] closing the app and re-opening for some reason forces me to select my "active budget" once more - instead it should remember the previously active budget and just show that

**Comment by Kidglove57** [comment] 2023-07-29 11:28
Ditto the above from my testing a couple of weeks back (at least for the Mac version).

I went back to running Actual as a desktop app using Unite 4 (https://www.bzgapps.com/). But I cannot do exports from that either.

**Comment by Shazib** [comment] 2023-07-29 17:00
Thanks @MatissJanis @Kidglove57, Unfortunately i dont have a Mac so can't work on any of the macOS specific bugs, but i will check all of these against the windows version and try to solve them there.

**Comment by MatissJanis** [comment] 2023-08-05 20:29
Small improvement for exporting: https://github.com/actualbudget/actual/pull/1468

Now if the export fails we will show a nice error message + will not crash the websockets. But this is still not really solving the export functionality (couldn't figure that out yet..)

**Comment by MatissJanis** [comment] 2023-08-05 20:32
This PR _might_ solve our issue though: https://github.com/WiseLibs/better-sqlite3/pull/1036

I'll wait for it to be merged and released before continuing investigations.

**Comment by Shazib** [comment] 2023-08-05 20:35
@MatissJanis Could the work i did in this [PR](https://github.com/actualbudget/actual/pull/1242) be of use here?

**Comment by MatissJanis** [comment] 2023-08-05 20:36
> @MatissJanis Could the work i did in this [PR](https://github.com/actualbudget/actual/pull/1242) be of use here?

What do you mean? That PR is already merged and in `master`.

**Comment by Shazib** [comment] 2023-08-05 20:38
> > @MatissJanis Could the work i did in this [PR](https://github.com/actualbudget/actual/pull/1242) be of use here?
> 
> What do you mean? That PR is already merged and in `master`.

Is the underlying problem a similar issue? That we can't call functions allocating memory outside the sandbox?

**Comment by MatissJanis** [comment] 2023-08-05 20:39
> Is the underlying problem a similar issue? That we can't call functions allocating memory outside the sandbox?

AFAIK: yes. Both `serialize` and `backup` is breaking because of [memory caging](https://www.electronjs.org/blog/v8-memory-cage). Though I might be totally wrong as my understanding here is based only off of half a days worth of research.

**Comment by Shazib** [comment] 2023-08-05 20:46
> > Is the underlying problem a similar issue? That we can't call functions allocating memory outside the sandbox?
> 
> AFAIK: yes. Both `serialize` and `backup` is breaking because of [memory caging](https://www.electronjs.org/blog/v8-memory-cage). Though I might be totally wrong as my understanding here is based only off of half a days worth of research.

Could the solution be to re-use the `exportDatabase` function i wrote there instead of `cloudStorage.exportBuffer` when running in electron?

**Comment by MatissJanis** [comment] 2023-08-05 20:49
> Could the solution be to re-use the `exportDatabase` function i wrote there instead of `cloudStorage.exportBuffer` when running in electron?

`cloudStorage.exportBuffer` is internally calling `exportDatabase`. And then the process hangs on `db.backup` [here](https://github.com/actualbudget/actual/blob/8ee4768f58181652e232d908c7394e634121c347/packages/loot-core/src/platform/server/sqlite/index.electron.ts#L119).

**Comment by shall0pass** [comment] 2023-08-06 14:11
> Goal templates seem to be working fine on the ubuntu version.

I've been using the electron app on Windows for a couple months now and goal templates are working the same as the Web version.

**Comment by thelazyoxymoron** [comment] 2023-09-22 07:31
Is the build no longer being generated? Can't seem to find any electron related artifacts in the linked actions page.

**Comment by Shazib** [comment] 2023-09-22 17:06
> Is the build no longer being generated? Can't seem to find any electron related artifacts in the linked actions page.

I can still see them for PR's

**Comment by MatissJanis** [comment] 2023-10-06 21:01
Socket reconnection has been merged and should be available in `edge`. Which means you should be able to use the electron app - make your computer go to sleep - and the app should still continue working after the computer starts up.

With this: I think all the issues have been resolved. Next we need to figure out a release process, signing, publishing to marketplaces, etc.

**Comment by Shazib** [comment] 2023-10-06 21:06
@MatissJanis amazing work!

Regarding windows builds, I think if you deploy to the Microsoft store, you do not need an expensive codesigning certificate from a verified authority, you upload the build to the store, and then they sign it with thier own certificate.

You need to create a certificate and sign the build you send to them, but this cert can be locally generated for free, as long as its linked with your developer account - so they can make sure you uploaded the build.

Actual would need an 'organisation' developer account which is a one-off lifetime fee of $99.

Of course this means that the builds distributed on github are signed but not verified. (but maybe we accept that for now, as the cost is quite a lot).

Apple I assume just requires a developer account?

**Comment by hackoder** [comment] 2023-11-05 18:38
@youngcw FYI, on linux, I was able to connect to my instance behind a self-signed cert by setting the following environment variable:

```
NODE_TLS_REJECT_UNAUTHORIZED=0 ./Actual-23.11.0-x86_64.AppImage
```

**Comment by lucastucious** [comment] 2023-11-16 14:17
Sorry, i mean, i've installed the Electron app [here](https://github.com/actualbudget/actual/actions/runs/6889326015), but all i have is a white screen 
![image](https://github.com/actualbudget/actual/assets/28046122/673c3fa6-a22a-4704-9184-13304e996327)

**Comment by Shazib** [comment] 2023-11-16 15:00
Can you try the latest stable build?

**Comment by lucastucious** [comment] 2023-11-16 15:09
Same issue with [this one](https://github.com/actualbudget/actual/actions/runs/6892412714)
I'm on win10 if it's relevant

**Comment by Shazib** [comment] 2023-11-18 01:18
Certainly does look like the windows builds are broken right now

**Comment by Shazib** [comment] 2023-11-18 01:58
@lucastucious give this one a go please https://github.com/actualbudget/actual/pull/1926

**Comment by MatissJanis** [comment] 2024-04-20 20:57
We will start publishing the electron app more publicly starting v24.5.0. Eventually it _might_ also end up in app-stores.

Closing this off as the electron app has been quite stable the last couple of months + the feedback for it has stopped coming in.

**If there are further issues - please open individual bug report issues.**

**Closed by MatissJanis** 2024-04-20 20:57 UTC
Labels: feedback
