### ISSUE TITLE
[Bug]: Hidden categories cannot be selected in category dropdown, even when searching.

### ISSUE THREAD

**Issue by rastographics** [actualbudget/actual#2761] opened 2024-05-15 19:18 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have several categories that are hidden because I don't need to interact with them on a daily regular basis.

However, occasionally I need to set a transaction to a category that IS hidden.

Currently, these are the steps I have to take:

1. Create New Transaction
2. Go to select Category, and realize that it is missing because it is hidden.
3. Cancel out of New Transaction.
4. Go to category in Budgets.
5. Unhide category.
6. Go back to New Transaction
7. Create New Transaction using the recently unhidden category.
8. Go back to Budgets.
9. Re-hide the category.

Something that is really nice for hidden categories in Budget view is that there is an option to show hidden categories, at which point they show up with a dark text that makes them "almost" invisible but enough you can read them.

If the user has this option of "Show hidden categories" enabled on their budget, can the hidden categories also be shown in the Category Dropdown for transactions? With the same UI styling that makes them blend into the background where they are "almost" hidden but not quite?

Of course, if the user has option "Show hidden categories" set to false, then the categories would also be completely hidden in the Dropdown as they are now.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by youngcw** [comment] 2024-05-15 19:27
Not including the hidden categories is by design.  If they are marked hidden shouldn't they be hidden?  If you don't want to see some categories on the budget table I would recommend a collapsed group instead of hiding them.  Hidden categories is really more for historical categories that are no longer used.

If you would like you could open a feature request for an option.  Since this is currently intended behavior I'll close this bug issue.

**Closed by youngcw** 2024-05-15 19:27 UTC
Labels: bug

**Comment by raiyni** [comment] 2024-07-16 13:25
> Not including the hidden categories is by design. If they are marked hidden shouldn't they be hidden? If you don't want to see some categories on the budget table I would recommend a collapsed group instead of hiding them. Hidden categories is really more for historical categories that are not currently used.
> 
> If you would like you could open a feature request for an option. Since this is currently intended behavior I'll close this bug issue.

What should be used in lieu of then? Because as is, there doesn't seem to be away to have a category be excluded from default reports. Having hidden categories function as an archive doesn't seem to make sense when the normal user would just assume it's *hidden* from reports?
