### ISSUE TITLE
[Bug]: Scheduled transactions being posted immediately instead of showing up as pending/missed

### ISSUE THREAD

**Issue by joaociocca** [actualbudget/actual#1010] opened 2023-05-07 15:26 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Scheduled transactions show up as upcoming when their date is drawing near, as expected... but when that day arrives, instead of showing up as Pending, or Missed, or whatever is the case, they now get added as if they had been posted.

![image](https://user-images.githubusercontent.com/6473725/236686713-a7137ac4-641c-41a2-96a4-8d5e715889b2.png)

I didn't post this transaction, but it already counts as if it had been. If I manually delete it, it then becomes "missing", as would be expected.

![image](https://user-images.githubusercontent.com/6473725/236686823-ebdcca7d-5222-431b-91b4-46fd023ec78d.png)

But I noticed this happening for a while now - I missed two scheduled transactions around 20th last month, and every time I open the budget I had to find them again and delete them because they were being posted... for a while, they would revert to missing. Last time, already after the month had changed, they didn't revert, they just vanished. It would be nice if they would stay as missing, as expected.

### What error did you receive?

No errors

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Linux

**Comment by j-f1** [comment] 2023-05-07 16:42
Do you have the “Automatically add transaction” checkbox checked for that schedule? That will auto-create the schedule.

**Comment by joaociocca** [comment] 2023-05-07 17:05
I agree and understand that it should auto-create the schedule, but at least before (I can't remember if the latest docker update or the previous one) it wouldn't automatically post these transactions, they'd show up as upcoming and when reaching their date or passing them, they'd change from upcoming to missed, until we posted them, as I've been taught in another issue here...

https://github.com/actualbudget/actual/issues/897#issuecomment-1508751809

**Comment by Kidglove57** [comment] 2023-05-07 17:47
I don't have any technical skille to input. However, as a regular user, I do have one weekly schedule that is NOT marked to auto-post. This schedule came around on Friday last. I can confirm that (for me at least) it behaved correctly and did not auto post.

I am using 2023-05.

**Comment by Kidglove57** [comment] 2023-05-08 06:26
Yes sorry - I should have written:
V23.5.0. Hosted on Fly

**Comment by joaociocca** [comment] 2023-05-08 13:05
that same transaction I had deleted and had returned to missed status, today is back as posted.
![image](https://user-images.githubusercontent.com/6473725/236831826-09176259-cfc8-49b2-8756-0d3c668856c5.png)

**Comment by j-f1** [comment] 2023-05-08 13:13
If you have the checkbox to auto create transactions checked for the schedule I think that is the expected behavior.

**Comment by joaociocca** [comment] 2023-05-08 13:25
should it be called "auto post transactions" then?

**Comment by Kidglove57** [comment] 2023-05-08 13:37
I thought I would just check the exact "check box" wording that is used when setting up a schedule to be auto posted at each due date.

 It is "Automatically add transaction". It seems clear enough for my use but very happy if an alternative wording is clearer to others.

**Comment by joaociocca** [comment] 2023-05-08 13:40
I understand them being two different actions - adding a transaction to the account is one thing, like when it shows as upcoming. Posting being a different one, when you change from upcoming/missed to an actual transaction... but it could be a bug in previous versions that made it behave as I understood, and it wasn't the expected behavior..?

**Comment by Kidglove57** [comment] 2023-05-08 13:44
Thanks for explaining further. I had not thought of it that way. I cannot recall a change in behavior since this was first added to the hosted app a year or two back.

I just created a new scheduled payment, due today,  but with the box unticked. The transaction immediately showed as "due" and "grayed out" in my account register but not as "posted".

**Comment by joaociocca** [comment] 2023-05-10 15:10
yeah, now that I unchecked automatically add transaction, they show up as expected...

![image](https://github.com/actualbudget/actual/assets/6473725/8f8e93f1-43fb-44d0-8928-bc20b7d94f8b)

Still think this description sounds misleading. But maybe it's just me.

**Comment by j-f1** [comment] 2023-05-10 15:13
If you have a better (concise) description we would be happy to change it!

**Comment by joaociocca** [comment] 2023-05-10 15:47
oh great, browser crashed and I lost the post. Let's start again.

Current text goes like this:

![image](https://github.com/actualbudget/actual/assets/6473725/12ce3098-2c3f-477f-a9f5-cc9960402b14)

"Automatically add transaction" and "If checked, the schedule will automatically create transactions for you in the specified account".

To me, this sounds like: the transaction won't be shown in the account screen if this box is unchecked. Something like... it'll be here, in the scheduled screen, to help you keep track of it. But it won't show up over there, in your selected account.

When we go to the account screen, and select an upcoming/due/missed scheduled transaction, the actions shown are:

![image](https://github.com/actualbudget/actual/assets/6473725/a9ab8b71-ecf9-4d9a-b325-7e0ebb65b4c5)

The action that transforms an scheduled transaction into an actual (no pun intended 😅) transaction is "Post transaction". Not "add transaction". And it wouldn't make sense to call it "add transaction", since that's already how it's calling including a new one.

> If you have a better (concise) description we would be happy to change it!

To answer this directly, I propose changing to: "Automatically post transaction" and "If checked, the schedule will automatically post transactions for you. All scheduled transactions are automatically added in the specified account"

I agree it's not that concise, but it doesn't seem to have a big impact, but explains better the feature:

![image](https://github.com/actualbudget/actual/assets/6473725/b99faf8c-65c5-4b38-aece-37ccf27433fc)

**Comment by joaociocca** [comment] 2023-05-10 18:57
Just found out I have another beef with the feature. When posting a missed scheduled transaction, it'll post with the original date. But that may kind of get lost in the sea of transactions? Would be nice to have two different actions for it: post on original date, and post today.

**Comment by rich-howell** [comment] 2023-05-10 18:59
> Just found out I have another beef with the feature. When posting a missed scheduled transaction, it'll post with the original date. But that may kind of get lost in the sea of transactions? Would be nice to have two different actions for it: post on original date, and post today.

This should go as a separate issue

**Comment by joaociocca** [comment] 2023-05-10 19:30
> > Just found out I have another beef with the feature. When posting a missed scheduled transaction, it'll post with the original date. But that may kind of get lost in the sea of transactions? Would be nice to have two different actions for it: post on original date, and post today.
> 
> This should go as a separate issue

#1020

**Comment by joaociocca** [comment] 2023-05-11 01:23
oh gods, there's more stuff wrong to scheduling and posting. So, I have this transaction that has max due date on the 16th. But I paid for it today. So I posted the upcoming scheduled transaction.

Actual decided that, no matter if it identifies as being part of the schedule (there's the schedule arrows beside it), and despite having been posted from the upcoming transaction, it cloned the upcoming into a new transaction but kept the upcoming transaction there...

![image](https://github.com/actualbudget/actual/assets/6473725/61c7c75a-dfc2-4b94-bd9c-35d1cdea7cbf)

And on the schedule, it doesn't recognize this as being paid.

![image](https://github.com/actualbudget/actual/assets/6473725/21c60d42-85b5-450a-8c96-4a2dfe6cab1b)

**Comment by shall0pass** [comment] 2023-05-11 01:47
I always looked at the italicized transactions from schedules as future possible entries (but not transactions yet). It's just a preview. If they're automatically entered or manually posted they count towards the account balances and become real entries.

What you're seeing in your last post is the 4 day window actual looks at to match transactions to a schedule.  Since you posted a transaction and then changed the date to 6 days early, you're no longer in the window and it won't match to the schedule.  I know it's by design, but I'm not sure what the reasoning was.

I wouldn't say anything is necessarily broken.  It's just not probably what you're used to.

**Comment by MatissJanis** [comment] 2023-08-26 14:12
I have to agree with @shall0pass that this works as-expected. 

Closing this off since the original issue is no-op.

**Closed by MatissJanis** 2023-08-26 14:12 UTC
Labels: bug
