### ISSUE TITLE
Cannot enter amount on mobile

### ISSUE THREAD

**Issue by gagegogan** [actualbudget/actual#2149] opened 2023-12-31 21:55 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

On a mobile device, specifically iOS you cannot focus the amount input to enter an amount. The keyboard will not open.

### What error did you receive?

None

https://github.com/actualbudget/actual/assets/10763068/b5377c2d-bd9a-4fc1-b62a-27de3f795062

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mobile Device

**Comment by Kidglove57** [comment] 2023-12-31 22:46
This is odd. I am using an iPhone 15 Pro Max with iOS 17 and I am able to add transactions. See clip attached.

Uploading RPReplay_Final1704062599.mp4…

**Comment by Kidglove57** [comment] 2023-12-31 22:48
https://github.com/actualbudget/actual/assets/93882449/327541e3-bc48-4606-97ee-7e5432fb7673

**Comment by gagegogan** [comment] 2023-12-31 22:58
I am on a iPhone 13 Pro Max. I tried it in Chrome and Safari. It just toggles between positive and negative.

**Comment by gagegogan** [comment] 2023-12-31 22:59
I tried it in the demo server. Please do the same

**Comment by gagegogan** [comment] 2023-12-31 23:26
Just another note. Locally installed Actual onto my laptop, and the same issue occurs. If I click on it with a mouse, it just toggles between positive and negative.

**Comment by gagegogan** [comment] 2023-12-31 23:42
Just tested version 23.11.0 and the keyboard opens

**Comment by gagegogan** [comment] 2023-12-31 23:45
OK. I just spun up my own server and it works fine. It's an issue with the demo website.

**Comment by rich-howell** [comment] 2024-01-01 06:41
@MatissJanis can you re-open this? The issue exists in the edge build releasing would cause an issue entering new transactions.

**Comment by Kidglove57** [comment] 2024-01-01 12:14
Good spot @rich-howell!
I can also reproduce this in Edge.
@gagegogan I was using the latest 2023-12 rather than Edge

**Comment by gagegogan** [comment] 2024-01-01 12:23
Reopened due to your comment @rich-howell

**Comment by MatissJanis** [comment] 2024-01-01 12:45
Thanks! This is definitely something we need to address before releasing v24.1.0

**Comment by MatissJanis** [comment] 2024-01-01 13:34
cc @joel-jeremy I suspect #2068 is breaking this. Do you have any quick ideas what might be at fault here? If not I'd be inclined to revert the PR in order to unblock the release.

**Comment by joel-jeremy** [comment] 2024-01-01 19:01
This might be caused by blur behavior in iOS

**Comment by joel-jeremy** [comment] 2024-01-03 16:39
@gagegogan Can you test if https://github.com/actualbudget/actual/pull/2166 fixes the issue?

**Comment by gagegogan** [comment] 2024-01-03 16:41
No change. The same issue still persists.

**Comment by gagegogan** [comment] 2024-01-03 16:43
This issue really baffles me. I was comparing edge to the latest stable release, and I don't see any breaking chains that could've caused it. Then again, I'm not familiar with the code base. Or react for that matter. I'm a vie guy.

**Comment by joel-jeremy** [comment] 2024-01-03 18:15
That's weird, it works just fine in Android. In your video I can also see that the amount is entering it's focused state.

**Comment by gagegogan** [comment] 2024-01-03 18:16
Is there an API that you can just call the keyboard to open on focus? Might be a quick fix. Additionally, do a platform check

**Comment by rich-howell** [comment] 2024-01-03 20:45
> That's weird, it works just fine in Android. In your video I can also see that the amount field is entering it's focused state.

The focus state changes but no keyboard appears. 

If I run it in the dev console on the desktop I can replicate it but if I type on my keyboard numbers are inserted so it seems to be a suppression of the keyboard appearing for some reason.

**Comment by rich-howell** [comment] 2024-01-03 20:49
I went back to some older open pulls and #2108 doesn't have the issue.

**Comment by joel-jeremy** [comment] 2024-01-03 22:07
What could possibly be suppressing keyboard in iOS? I have pushed an update on the PR, could you please try again?

**Comment by gagegogan** [comment] 2024-01-03 22:09
I don't see an updated link on the PR

**Comment by joel-jeremy** [comment] 2024-01-03 22:11
Just click on the same netlify link on the PR

**Comment by gagegogan** [comment] 2024-01-03 22:12
Same issue occurs

**Comment by gagegogan** [comment] 2024-01-03 22:12
I wonder if the button is interfering in someway

**Comment by joel-jeremy** [comment] 2024-01-03 22:25
> I wonder if the button is interfering in someway
What do you mean?

I tried using a ref to focus on the input. Maybe that will force the keyboard to show up - can you try the link again? (Sorry I don't have an iOS device so I'm not able to test on my own)

**Comment by HansiWursti** [comment] 2024-01-03 22:31
Hi,

I surfed a little bit at the Web.

Is this maybe the problem?

https://stackoverflow.com/a/35768655/8741781

That the focus is not directy triggered by an user Input and iOS handle the focus in an interesting way? 

Thank you!

**Comment by gagegogan** [comment] 2024-01-03 22:37
Still does not work. But I was referencing the button that caused the focus onto the input.

**Comment by joel-jeremy** [comment] 2024-01-03 22:51
> https://stackoverflow.com/a/35768655/8741781

This might be worth looking into. Pushed another update on the PR.

**Comment by gagegogan** [comment] 2024-01-03 22:58
Still not working.

**Comment by joel-jeremy** [comment] 2024-01-03 23:24
I guessing the `onRequestActiveEdit` callback is causing the issue. It runs the edit action in an effect instead of synchronously from the button click event handler. I have updated the hook to run the action synchronously.

**Comment by rich-howell** [comment] 2024-01-04 07:52
> What could possibly be suppressing keyboard in iOS? I have pushed an update on the PR, could you please try again?

It works on iOS now the keyboard shows again and I can enter a transaction.

**Comment by Kidglove57** [comment] 2024-01-04 10:24
Yes, confirmed all working now. Thanks for your perseverance!

**Comment by gagegogan** [comment] 2024-01-04 12:53
Also working for me.

**Comment by joel-jeremy** [comment] 2024-01-04 23:23
Re-opening this since the PR hasn't been reviewed and merged yet

**Comment by MatissJanis** [comment] 2024-01-05 17:08
Fix was merged

**Closed by MatissJanis** 2024-01-05 17:08 UTC
Labels: bug, regression
