### ISSUE TITLE
[Bug]:  Duplicate Transactions from Bank

### ISSUE THREAD

**Issue by Phil89a** [actualbudget/actual#2539] opened 2024-04-02 11:08 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [X] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [X] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

I reported a problem last week about 100 or so duplicated transactions - this was looked into and suggested GoCardless needed to look into it.

GoCardLess are asking for the account_id I am connecting with "If you are connecting to the API via our portal. Then account_id will be visible in the url when you press view transactions. Can you please share this url with me?"

When I mentioned that it was from Actual, they responded....

" we recommend contacting the Actual Budget Support Team. And either they need to share account_id with you and then you share with us or their team needs to raise request for us separately. Without id's unfortunately I'm not able to detect your session in our system and look more into depth in the problem. "

Can you help?

### What error did you receive?

N/A

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Operating System

Mac OSX

**Comment by MatissJanis** [comment] 2024-04-02 17:22
👋 There is no "Actual Budget support team". There is, however, a community of helpful folks on Discord.

Please use Discord for support requests. 

Closing this as this is not a bug report.

**Closed by MatissJanis** 2024-04-02 17:22 UTC
Labels: bug

**Comment by Phil89a** [comment] 2024-04-02 20:15
HiWill the community on Discord know what account-id Actual uses for its connection to GoCardless?I assume this wouldn’t be “public” knowledge so I asked here.  You suggested I talked to GoCardLess support but they won’t talk to me unless I have the account-id.So I seem caught in a loop here ☹️Thanks Sent from my iPadOn 2 Apr 2024, at 18:23, Matiss Janis Aboltins ***@***.***> wrote:﻿
👋 There is no "Actual Budget support team". There is, however, a community of helpful folks on Discord.
Please use Discord for support requests.
Closing this as this is not a bug report.

**Comment by MatissJanis** [comment] 2024-04-02 20:46
Actual is a local-first product. So all the data is hosted on your device/server. This includes the account-id - it's available on your end.

But: you need a bit of know-how in order to access it. That's where the community will help you out - to figure out how to get to the account-id on your end.
