### ISSUE TITLE
[Bug]: Reconciliation state persists when selecting a new account

### ISSUE THREAD

**Issue by TomAFrench** [actualbudget/actual#1474] opened 2023-08-06 15:16 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Currently if you're reconciling an account with a target balance then the reconciliation doesn't stop when you switch which account you're viewing. This results in a completely bogus target balance being shown for this new account.

Reproduction:
1. Start reconciling `Account A` and provide a target balance `B`.
2. Select a `Account B` from the sidebar.
3. Observe that `Account B` is now in a reconciliation state with target balance `B`

We should turn off the reconciliation state whenever we switch accounts to address this.

### What error did you receive?

N/A

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Linux

**Comment by MatissJanis** [comment] 2023-08-06 15:18
Duplicate of: https://github.com/actualbudget/actual/issues/1327

**Closed by MatissJanis** 2023-08-06 15:18 UTC
Labels: bug

**Comment by TomAFrench** [comment] 2023-08-06 15:22
Ah apologies, I searched for "reconciliation" rather than "reconcile" so that didn't show up.
