### ISSUE TITLE
[Bug]: All sub-transactions in a split transaction are selected even when a filter is applied

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#381] opened 2022-10-30 19:32 UTC
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

If I filter an account view by category, and then "select all", all of the items in a split transaction are selected including those that don't match the filter. This throws off the expected selected balance of the filter. I would expect only the filtered transactions to be selected within a split transaction.
![197346691-91f46bcd-2613-41dc-b6a4-306ab15a9f72](https://user-images.githubusercontent.com/20625555/198897938-9fe7ead8-7dc1-4b3c-84d7-50b1f5c8c5bb.png)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by Kidglove57** [comment] 2022-10-31 07:50
I agree this has been a serious issue with filters ever since they were introduced over two years ago.

**Comment by CharlesEkkel** [comment] 2022-10-31 10:06
Is there any use case for still being able to select absolutely everything, including the sub-transactions? Or is it safe to just restrict select-all to just selecting top-level transactions?

**Comment by j-f1** [comment] 2023-06-16 00:36
It looks like this is a duplicate of #283.

**Closed by j-f1** 2023-06-16 00:36 UTC
Labels: bug, transactions
