### ISSUE TITLE
[Feature Request] Lock transactions after reconciling

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#498] opened 2023-01-22 18:22 UTC
### Discussed in https://github.com/actualbudget/actual/discussions/358

<div type='discussions-op-text'>

<sup>Originally posted by **bverkron** October 14, 2022</sup>
Would be nice if after reconciling it would lock transactions so they give you a warning like they do in YNAB. Makes it easier to trace back issues that arise because you know you don't have to go back beyond a certain point (where it was last reconciled and locked). Prevents changing already reconciled transactions and "unreconciling" things too easily.

![image](https://user-images.githubusercontent.com/19174503/195738866-bad177f9-31d2-45c0-a0b5-8c3b9e68c032.png)

![image](https://user-images.githubusercontent.com/19174503/195738813-56a92ebb-56e1-4788-a3f4-a7064f719e5b.png)
</div>

**Comment by MatissJanis** [comment] 2023-01-29 19:14
Closing as duplicate of: https://github.com/actualbudget/actual/issues/558

**Closed by MatissJanis** 2023-01-29 19:14 UTC
Labels: needs triage, feature
