### ISSUE TITLE
[Bug]: Desktop Client no longer able to export budget files

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#2907] opened 2024-06-19 22:42 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I can no longer export budget files using either the linux appimage or flatpak.  I haven't tested either windows or mac to see if they have the same issue.

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Linux

**Comment by MatissJanis** [comment] 2024-06-20 16:35
Broken on Mac too (using v24.6.0 release)

**Comment by MatissJanis** [comment] 2024-06-20 20:47
Did a bit of investigation here.

The error: `unable to open database file`.

Comes from SQLite. My current hypothesis is that the backend is no longer able to open the local sqlite file after upgrade of Electron (possibly permission issue?).

Breaking function: https://github.com/actualbudget/actual/blob/5b1a730f111d6a670d336d573bddb95c2a1e7e96/packages/loot-core/src/server/cloud-storage.ts#L119

My investigation here stops at this point. If anyone has time/ability - feel free to pick it up.

**Comment by youngcw** [comment] 2024-06-22 16:06
So I tried reverting #2763 and I could export the file.  That when back to an older electron version that is no longer supported.  I also noticed that the newer version of electron that that PR set lists node v20 as the version to use.  I don't know if updating the project to node v20 would help or not.

**Comment by MikesGlitch** [comment] 2024-06-23 17:24
Eek. Just chiming in to say It works on Windows.

**Comment by MikesGlitch** [comment] 2024-06-23 17:54
I highly suspect this: 

https://github.com/electron/electron/issues/42621


Seems to fail at       

[const fileLocation = dialog.showSaveDialogSync({ title, defaultPath ](https://github.com/actualbudget/actual/blob/6a21f8e3de7fda25afe4345a0af3aad6d90d4966/packages/desktop-electron/index.js#L313)

**Comment by youngcw** [comment] 2024-06-25 16:39
#2925 only fixed linux but mac is still broken.

**Comment by MikesGlitch** [comment] 2024-06-25 16:53
Cool. I don't have a mac so I can't fix that one. 

I'm not sure if the Electron update would have broken that, it looks like a sqlite error. 

I'd be interested to know if it fails when importing a budget, or exporting transactions (from account area).

I found this, which is suggesting it may be permissions related - something about the app needing full disk access to write to the disk: https://stackoverflow.com/questions/67430680/sqlite3-operationalerror-unable-to-open-database-file-on-mac-os-external-hard

**Comment by MatissJanis** [comment] 2024-06-25 19:01
Thanks! Testing using the latest `master`:

> Does it fail when importing a budget

✅ importing works as expected

> Does it fail when exporting transactions (from an account)

✅ exporting single account transactions works

> Does it fail when running the unpackaged version? E.g. Running yarn start:desktop

✅ no failures when running un-packaged version

🔴 giving the app "full disk access" permissions (manually) did not fix the issue

**Comment by MikesGlitch** [comment] 2024-06-25 19:41
Cool, so that narrows it down then. We had two separate issues,
- [x] The one that got fixed earlier to do with writing the file on linux - fixed
- [ ] This one which is preventing macs from opening the database - needs debugging

It's probably something around here:  https://github.com/actualbudget/actual/blob/5b1a730f111d6a670d336d573bddb95c2a1e7e96/packages/loot-core/src/server/cloud-storage.ts#L143

Would need to check the values of rawDbContent to see if it received the content

A possibility is the openDatabase implementation is wrong - it's slightly different from the web one.

**Electron:**
https://github.com/actualbudget/actual/blob/48f5880f1dc260ff8a791cdb87aa4ce947df54f6/packages/loot-core/src/platform/server/sqlite/index.electron.ts#L102

**Web:**
https://github.com/actualbudget/actual/blob/48f5880f1dc260ff8a791cdb87aa4ce947df54f6/packages/loot-core/src/platform/server/sqlite/index.web.ts#L162

If the problem lies here, it must have always failed on Mac. 

Do we know if this was working on Mac before we did the Electron update?

**Comment by MatissJanis** [comment] 2024-06-25 20:26
Quick update: went 5 months back in history to try and find offending commit. No luck. And I'm absolutely sure I've tried doing an export in the last 5 months and it worked.

Which leads me to believe this might be something new after upgrading the OS.

**Comment by xinomoreno** [comment] 2024-06-29 17:26
0 experience with typescript, node, electron....trying to learn. Maybe I'm doing something wrong and this is not a good trail.
I built the electron packaged app with build:desktop on a M1 mac and then executed the app. I wished i could have tried to export database but couldn't even open it.  So I tried to lldb the app, got this exception:
`
 (
[Exception] Error: dlopen(/var/folders/nz/zy2d1fbs7fsd7kg550fzw2tc0000gn/T/.com.actualbudget.actual.eknH2s, 0x0001): tried: '/var/folders/nz/zy2d1fbs7fsd7kg550fzw2tc0000gn/T/.com.actualbudget.actual.eknH2s' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/nz/zy2d1fbs7fsd7kg550fzw2tc0000gn/T/.com.actualbudget.actual.eknH2s' (no such file), '/var/folders/nz/zy2d1fbs7fsd7kg550fzw2tc0000gn/T/.com.actualbudget.actual.eknH2s' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/private/var/folders/nz/zy2d1fbs7fsd7kg550fzw2tc0000gn/T/.com.actualbudget.actual.eknH2s' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/nz/zy2d1fbs7fsd7kg550fzw2tc0000gn/T/.com.actualbudget.actual.eknH2s' (no such file), '/private/var/folders/nz/zy2d1fbs7fsd7kg550fzw2tc0000gn/T/.com.actualbudget.actual.eknH2s' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1489:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2441)
    at Module.load (node:internal/modules/cjs/loader:1214:32)
    at Module._load (node:internal/modules/cjs/loader:1030:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1242:19)
    at require (node:internal/modules/helpers:176:18)
    at bindings (/Users/miguelcalduchnos/dev/actual/packages/desktop-electron/dist/Actual.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
    at new Database (/Users/miguelcalduchnos/dev/actual/packages/desktop-electron/dist/Actual.app/Contents/Resources/app.asar/node_modules/better-sqlite3/lib/database.js:48:64) {
  code: 'ERR_DLOPEN_FAILED'
}`

Could it be related to the same export issue?

**Comment by MikesGlitch** [comment] 2024-06-29 19:13
> mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

Hey, try this https://github.com/WiseLibs/better-sqlite3/issues/968#issuecomment-1465320102

**Comment by xinomoreno** [comment] 2024-07-02 22:47
Seems my problem was in the other direction, actual was x86 app and sqlite3 is arm as my node.js. So I built actual as arm64 and sorted it out. I could reproduce the issue with export but when executing with lldb, exports works like a charm 😢

**Comment by MikesGlitch** [comment] 2024-07-11 11:07
I have a potential fix for this in this PR: https://github.com/actualbudget/actual/pull/3015

It changes the way the bundle is built. I think it would be worth trying again on that build just to see if that's the issue.

Downloads are here: https://github.com/actualbudget/actual/actions/runs/9861102275

**Comment by MatissJanis** [comment] 2024-07-13 11:43
macos Soma 14.5

🔴 "export data" still broken using the CI build from #3015 
🔴 "export data" still broken using a local build of #3015
🔴 "export data" still broken using a local build of #3015 + upgrading better-sqlite3

Sadly this doesn't fix the issue. Though the error is still the same: `unable to open database file`. I'm guessing some recent osx security upgrade has hardened something.. which breaks exports. But I haven't had a chance to dig deeper here.

**Comment by xinomoreno** [comment] 2024-07-13 16:49
Working in debug made me thinking of a race condition...

**Closed** 2024-08-14 12:38 UTC
Labels: bug, help wanted, electron
