### ISSUE TITLE
Forecasting Support

### ISSUE THREAD

**Issue by elInfidel** [actualbudget/actual#716] opened 2023-03-01 09:51 UTC
Is there an intention to add the ability to forecast into the future with charts. For example, if I had $100 and I had a monthly recurring deduction of $10 in a 5-month forecast I would see my money drop to $50. Something that would help you see if your current budget is sustainable into the longer-term future. Much more useful with lots of deductions and additions occurring monthly obviously.

Unless this is already a thing and I'm missing it on the version I'm using. I'm only able to see in the past up to the current date.

**Comment by MatissJanis** [comment] 2023-03-01 19:14
Duplicate of https://github.com/actualbudget/actual/issues/517

**Closed by MatissJanis** 2023-03-01 19:14 UTC
Labels: needs triage
