### ISSUE TITLE
[Bug]: When importing a CSV file an error occurs

### ISSUE THREAD

**Issue by natrlhy** [actualbudget/actual#3227] opened 2024-08-09 17:20 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When I try to import a CSV file, I get an error in the Web App.
I was able to import a few CSV's prior to getting this error, but now, no matter what CSV I try to import, even previously working ones, I continue to get this error. I've tried clearing my cache, using a different browser and even had a successful import on my iPad using Safari but then right after, I get the same error.

I'm using the `edge` build as of the last commit just over 20 hours ago.

CSV file:
[failing_import_Activity20231231_20240501_20240809.CSV](https://github.com/user-attachments/files/16565439/failing_import_Activity20231231_20240501_20240809.CSV)

Console file: 
[console-export-2024-8-9_10-12-31.txt](https://github.com/user-attachments/files/16564845/console-export-2024-8-9_10-12-31.txt)

### What error did you receive?

Something internally went wrong. You may want to restart the app if anything looks wrong. Please report this as a new issue on Github.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox & Edge

### Operating System

Windows 11

**Comment by natrlhy** [comment] 2024-08-09 22:09
This had previously been working until I updated to last nights `egde` commit. Maybe something to do with https://github.com/actualbudget/actual/commit/30a70f56270d22577c1f2e3d99a3113e8219a28d ?

**Comment by psybers** [comment] 2024-08-10 02:36
Caused by this commit: https://github.com/actualbudget/actual/commit/30a70f56270d22577c1f2e3d99a3113e8219a28d

**Comment by latetedemelon** [comment] 2024-08-11 00:35
I'm experiencing this as well, using OFX too it seems.

@MatissJanis - I know we've had to roll back [30a70f5](https://github.com/actualbudget/actual/commit/30a70f56270d22577c1f2e3d99a3113e8219a28d) before, do we need to look at it again?

**Comment by psybers** [comment] 2024-08-11 00:38
Dupe of #3211.

**Comment by pmoon00** [comment] 2024-08-11 07:48
@psybers @latetedemelon I've created a [PR](https://github.com/actualbudget/actual/pull/3232) that resolves the issue.

**Closed** 2024-08-11 17:37 UTC
Labels: bug

**Comment by natrlhy** [comment] 2024-08-11 19:24
Thanks all. Hopefully this makes it into tonight's Edge build.
