### ISSUE TITLE
[Bug] Budgeted column doesn't update based on upcoming Schedules

### ISSUE THREAD

**Issue by gravelfreeman** [actualbudget/actual#1572] opened 2023-08-23 02:02 UTC
Hello,

I think this is a bug, at least it doesn't make sense to me how it's working at the moment.

I spent quite some time adding all my upcoming payments under the Schedules tab. After adding my schedules to a category by modifying the rule, I was surprised that I had to manually add them in the Budgeted column.

I think the current behaviour is so that the schedule task creates an entry in the database and then that expense will appear under the Spent column prior to the category line you've set the rule to.

The same logic should apply to the Budgeted column; since I know it'll be an expense and that I took the time to add it as a schedule, I'm expecting to see it there, without manual intervention.

I hope this makes sense, long life to actual server, you guys rock!

**Comment by MatissJanis** [comment] 2023-08-23 06:44
Duplicate of https://github.com/actualbudget/actual/issues/1569

**Closed by MatissJanis** 2023-08-23 06:44 UTC
