### ISSUE TITLE
[Bug]: error message while syncing

### ISSUE THREAD

**Issue by nfranken** [actualbudget/actual#2798] opened 2024-05-25 06:06 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

error message:
'we had trouble syncing your changes. Please report this as a bug by opening  a GitHub issue

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by MatissJanis** [comment] 2024-05-25 09:07
👋 How can we reproduce this issue?

**Comment by nfranken** [comment] 2024-05-25 09:32
Hi,

this error occurred once. Now it works flawlessly. Maybe it happened when i had actual server open and changing something when at the same time I had actual (web connected) running on my iPhone .
Thanks for the feedback.
Regards
Nick Franken
Great program!! Very happy with it.

**Comment by MatissJanis** [comment] 2024-05-29 18:46
Great that it works now. I'll close this off since 1) there is no way to reproduce and 2) the issue auto-fixed itself on your end, so you're not blocked by anything.

Thanks for the report nonetheless.

**Closed by MatissJanis** 2024-05-29 18:46 UTC
Labels: bug, needs info

**Comment by nfranken** [comment] 2024-05-29 18:49
I have to thank you for listening.
Regards Nick Franken
