### ISSUE TITLE
[Feature Request] Set finish condition to repeating transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#506] opened 2023-01-22 18:26 UTC
### Discussed in https://github.com/actualbudget/actual/discussions/276

<div type='discussions-op-text'>

<sup>Originally posted by **arguser** March 11, 2022</sup>
## Description

Have the option to set  the amount of cycles (repeats) for a repeating transaction.

## Use Case
On many countries it's common to pay the full price of a product distributed in a fixed amount of months, 3, 6, 9, 12. As a user when making such transaction would be helpful to establish the end of the repeating input, so you wouldn't have to remember to remove a transaction once the period has ended.

## Solution

How I imagine this being implemented:

1. Input a transaction (spend) of let's say $100
2. Mark transaction as repeating
3. Set it to Monthly
4. Set it to 3 Cycles to record only transaction and repeat it on the following two months.
5. Once 3 iterations of the transaction occur, stop scheduling it.</div>

**Comment by MatissJanis** [comment] 2023-01-29 19:42
Duplicate of: https://github.com/actualbudget/actual/issues/308

**Comment by j-f1** [comment] 2023-01-29 20:57
Those seem to be different — this one is about stoping a schedule automatically while #308 is about changing the interval it which a schedule repeats.

**Comment by MatissJanis** [comment] 2023-01-29 21:01
My bad, linked the wrong thing.

Here's the PR with ongoing work to make "stop transaction scheduling after X transactions" work: https://github.com/actualbudget/actual/pull/407

**Closed** 2023-05-01 19:50 UTC
Labels: schedules, feature, needs votes
