### ISSUE TITLE
[Bug]: Pull to refresh on mobile does not prevent tap on budget row

### ISSUE THREAD

**Issue by JukeboxRhino** [actualbudget/actual#3214] opened 2024-08-07 14:10 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

How to reproduce:
1. Go to https://demo.actualbudget.org on a mobile device
2. View demo file
3. Pull down to refresh

Pulling down to refresh should prevent the tap from registering on the budget row/category header that was pulled down on. Instead, when you lift up your finger after pulling down, the budget category opens as if you tapped on it. This  behavior seems to have been newly introduced in the last release.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mobile Device

**Comment by psybers** [comment] 2024-08-07 14:41
I can confirm this occurs on the 24.8.0 release.

**Comment by theMubashir919** [comment] 2024-08-08 05:24
I can confirm. I am also facing this issue in the mobile PWA version.

**Comment by MatissJanis** [comment] 2024-08-28 20:19
I am able to reproduce as well on Safari + iOS. Most likely related to the Button migration we're running.

Haven't been able to find a fix for this yet. cc also @joel-jeremy for visibility

**Comment by ansuckynoob** [comment] 2024-09-01 17:35
Also experiencing this in Brave/PWA on Android.

**Comment by twk3** [comment] 2024-09-02 17:24
@MatissJanis I can repro on demo, but not on edge. It looks like this may already be fixed in master? For others, is it working on https://edge.actualbudget.org/ ?

**Comment by MatissJanis** [comment] 2024-09-02 17:25
I can still repro on edge @twk3

**Comment by ansuckynoob** [comment] 2024-09-02 22:28
On edge, with Brave + Android, this behavior seems fixed when pulling down on the category labels, but not when pulling down on any of the numeric columns.

**Comment by twk3** [comment] 2024-09-03 14:42
> behavior seems fixed when pulling down on the category labels, but not when pulling down on any of the numeric columns.

Ahh, this is what I am seeing as well.

**Closed** 2024-09-18 13:28 UTC
Labels: bug, help wanted, responsive, regression
