### ISSUE TITLE
[FEATURE REQUEST] Add confirmation modal when delete rules is clicked

### ISSUE THREAD

**Issue by winklevos** [actualbudget/actual#194] opened 2022-08-21 02:57 UTC
Currently, if you have selected rules and click delete there is no confirmation. As this delete button is next to the create, there is room for error which would not be ideal

![image](https://user-images.githubusercontent.com/30995408/185773341-59682df1-cccb-4d0b-9232-7956495ca6bd.png)

**Comment by rich-howell** [comment] 2022-08-22 16:11
This seems like a valid request, I have marked it as an **enhancement** for now.

**Comment by j-f1** [comment] 2022-08-31 17:35
I’m pretty sure undo works here, so maybe a confirmation isn’t necessary?

**Comment by rich-howell** [comment] 2022-08-31 17:38
This is a duplicate of https://github.com/actualbudget/actual/discussions/197 so I will go ahead and close this one out.

**Closed by rich-howell** 2022-08-31 17:38 UTC
Labels: duplicate, enhancement
