### ISSUE TITLE
[Bug]: Don't allow duplicate category group names

### ISSUE THREAD

**Issue by Shazib** [actualbudget/actual#1920] opened 2023-11-17 14:47 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

We should not allow duplicate names for category groups

**Comment by TomAFrench** [comment] 2023-12-03 19:15
Duplicate of https://github.com/actualbudget/actual/issues/1829

**Closed** 2024-02-02 20:10 UTC
Labels: bug, good first issue, help wanted, budgeting
