### ISSUE TITLE
Schedule Posting - Rules not being applied

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/actual#1775] opened 2023-10-09 09:23 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I have rules enabled to add a category and note to a scheduled transaction on posting. These rules were not applied on two transactions posted today. I have tested this further as follows:
I) I removed the option to move the transaction to after the weekend. When I did this the category and note were correctly applied.
2) Therefore it seems that the new option to post before or after a weekend is causing the problem
3) I am able to reproduce this error by advance posting a number of future scheduled  transactions
4) HOWEVER I cannot reproduce this error on all schedules!
5) I have tested in Safari and Brave.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by shall0pass** [comment] 2023-10-11 11:21
I'll add to this report, though I'm not certain if it's related.  

I have a schedule that gets automatically added on 3 specific days of the month.  Today, the 11th, I checked my ledger and I saw that the schedule was posted but also showed it as upcoming and 'due'.  I opened the budget on a different device and saw I had two posted transactions and one upcoming showing 'due', giving the impression that the link between the schedule and posted transaction was somehow lost.  I tried navigating to the schedules page, and chose 'post transaction' from the affected schedule, and while it did post the transaction it was not marked as 'paid'.

I unfortunately am not able to reproduce this on demo.actualbudget.org and am not certain if Rules was a factor.

Within the schedule editor, the dialog for 'Linked transactions' does not include todays transactions, but under 'Find matching transactions' they are listed along with the circular arrows next to the payee name.

**Comment by shall0pass** [comment] 2023-10-11 11:33
Quick follow up:  I was able to relink the transaction to the schedule so it behaves appropriately again.

1.  Select the transaction in the ledger that is behaving incorrectly.
2. Select from the menu -> Unlink schedule
3. Select from the menu (while transaction is still selected) -> Link schedule
4. Select the schedule from the pop up window

**Comment by Kidglove57** [comment] 2023-10-11 12:47
@shall0pass Thank you for the investigation! You inspired me to search further for a solution to my issue. Delinking and relinking the schedule unfortunately did not work for me. 

However, I remained puzzled as to why some of my transactions posted with the rules correctly applied and some did not.

Here is the solution I found. For context this is where I have adjusted a schedule to "post after a weekend"
1) My schedules that were posting correctly all had one thing in common. In the rule, one of the conditions was set as "the date is approx ...."
2) The schedules that failed to apply the rule had this condition set as "the date is ....". Therefore the rules failed when the date moved before or after a weekend.

LESSON: Ensure all relevant schedules have the date condition set as "The date is approx..."

**Closed** 2023-10-11 12:47 UTC
Labels: bug

**Comment by shall0pass** [comment] 2023-10-11 13:04
That's interesting.  Maybe there's some room for improvement there.  Automatically converting a linked rule to "The date is approx..." when using "move schedule" option could keep this from happening.

**Comment by youngcw** [comment] 2023-12-05 14:36
I think I had the same thing happen just now, but I manually posted the schedule and it still didn't clear out the upcoming schedule line

**Comment by shall0pass** [comment] 2023-12-05 14:59
I'm a little slow.  I wasn't finding the 'date is approx' item until today.  Any idea what the time window is on that option?  I wonder if the before/after weekend option is shoving me outside the window, although the schedule it happened to me on didn't use that feature.

I'm going to change my schedule that had issues to use 'date is' and see if that resolves it.

**Comment by Kidglove57** [comment] 2023-12-05 16:22
“Date is” was what caused me the original problem (see my earlier comment) and appeared to be because “Date is” left no flexibility for the logic to deal with before or after a weekend and the rule could not be applied. Since I changed everything to “Date is Approx” (two months ago) my rules have consistently been applied on posting.

My memory may be faulty but I believe the window is 2 days either side. Anything outside of that appeared to recreate the scheduled transaction.

**Comment by shall0pass** [comment] 2024-01-04 00:53
Just to bump this, I've now had multiple schedules the last couple days that did not post automatically and used to fine.
