### ISSUE TITLE
[Feature] Dashboard and Charts

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#503] opened 2023-01-22 18:25 UTC
### Discussed in https://github.com/actualbudget/actual/discussions/402

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** December 12, 2022</sup>
Adding this here to capture ideas for charts in Actual.

Some ideas in https://github.com/actualbudget/actual/discussions/39 </div>

**Comment by MatissJanis** [comment] 2023-02-10 19:04
Closing as duplicate of: https://github.com/actualbudget/actual/issues/507

**Closed by MatissJanis** 2023-02-10 19:04 UTC
Labels: needs triage, reports, user-interface, feature
