### ISSUE TITLE
[Feature Request] Add ability to reconcile accounts

### ISSUE THREAD

**Issue by biohzrddd** [actualbudget/actual#494] opened 2023-01-22 16:06 UTC
Actual doesn't currently have the ability to reconcile accounts. I use cleared/uncleared state to show a transaction has posted to my bank account, then reconciling after a bank account statement comes out where I can confirm my records match theirs. 

Starting list of work items I can see needed:
- add a third state to each transaction indicating uncleared/cleared/reconciled
- Add a reconcile button to each account page
- Add a reconcile GUI that shows transactions to a certain date and allows selecting/unselecting them as reconciled. Possibly copying the current transactions layout  as a start.
- add a new filter to show/hide reconciled transactions on account view

**Comment by rich-howell** [comment] 2023-01-22 16:51
This is also raised in #358

**Comment by MatissJanis** [comment] 2023-03-30 19:36
Closing as duplicate of https://github.com/actualbudget/actual/issues/558

**Closed by MatissJanis** 2023-03-30 19:36 UTC
Labels: transactions
