### ISSUE TITLE
[Feedback] Spending Report

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#2820] opened 2024-06-02 19:14 UTC
Please use this thread to submit any feedbak you have for the spenind report.

It can be found in experimental features. Cheers!

**Comment by carkom** [comment] 2024-06-02 21:02
Known issue: off budget payments are being counted. Need to remove them.

**Comment by carkom** [comment] 2024-06-02 21:04
Suggestion: Add "last month" as the primary line so you can see how the month ended during the 1st week of the following month.

**Comment by glowtape** [comment] 2024-06-03 15:10
The off-budget accounts appears to my issue in #2810 . When I add them into the filter one by one, said error builds up. What's however curious is why they get excluded by filtering out an unused category.

**Comment by jsehnoutka** [comment] 2024-06-03 16:31
Suggestion: Add ability to toggle between Payment/Deposit to monitor income as well (might also be duplicated into separate Monthly Income report)

**Comment by latetedemelon** [comment] 2024-06-03 18:31
Suggestion: When the month turns over you no longer can review the spening vs. the previous month.  I'd suggest allowing the user to review the previous months spending against the prior months as well.

**Comment by ogielee** [comment] 2024-06-06 12:40
Suggestion: Add income in Data table view and a surplus or deficit to highlight the difference between income and total expenses.

**Comment by shall0pass** [comment] 2024-06-09 19:14
When filtering by category, the only option is to compare to last month.   The option to see the 3 month average disappears.

**Comment by carkom** [comment] 2024-06-10 11:46
> When filtering by category, the only option is to compare to last month. The option to see the 3 month average disappears.

The logic follows that you need 3 months of data for the average button to be shown. If your filter does not have transactions for the previous 3 months then average is not possible to calculate.

Example: If you filter to a category that only has transactions for this month and last month then there should not be an "average" option as there wouldn't be enough data to calculate an average.

**Comment by Waseh** [comment] 2024-06-10 12:11
I'm only able to compare to last month. Is this intended? I have almost two years of data in Actual yet when I push (what seems to be a button) last month nothing happens.

**Comment by shall0pass** [comment] 2024-06-10 16:26
> > When filtering by category, the only option is to compare to last month. The option to see the 3 month average disappears.
> 
> The logic follows that you need 3 months of data for the average button to be shown. If your filter does not have transactions for the previous 3 months then average is not possible to calculate.
> 
> Example: If you filter to a category that only has transactions for this month and last month then there should not be an "average" option as there wouldn't be enough data to calculate an average.

I was looking at my grocery category and have 10 years of data.  The 3 month window isn't  a problem.  I still only get an option for last month.

**Comment by carkom** [comment] 2024-06-10 18:46
> Edit: I am using 24.6.0.... the edge release doesn't have this issue. Please disregard.

Oh cheers! I was about to ask about edge as it was recently fixed. Thanks for confirming!

**Comment by tcjoshuafan** [comment] 2024-06-14 05:23
Suggestion: Add option for saved/default applied filters persistent between loads/refreshes. There might be a way to do this via custom reports, but as a QOL setting OOTB for most users.

chickenscratch figma mock:

![Group 127](https://github.com/actualbudget/actual/assets/22987749/3f686cab-fab9-4ecb-aaed-ea85095a1a72)

Loving the solution btw, have it hosted on Pikapod and it's really helped. Just wish I could trigger updates myself rather than waiting for Pikapod to test first but I'll take what I can get :P

**Comment by tcjoshuafan** [comment] 2024-06-14 05:25
Suggestion: Add option for saved/default applied filters persistent between loads/refreshes. There might be a way to do this via custom reports, but as a QOL setting OOTB for most users.

chickenscratch figma mock:
![Group 128](https://github.com/actualbudget/actual/assets/22987749/93c2b650-a0c2-458c-b29a-e22c207af711)


Loving the solution btw, have it hosted on Pikapod and it's really helped. Just wish I could trigger updates myself rather than waiting for Pikapod to test first but I'll take what I can get :P

**Comment by carkom** [comment] 2024-06-14 06:23
> Suggestion: Add option for saved/default applied filters persistent between loads/refreshes. There might be a way to do this via custom reports, but as a QOL setting OOTB for most users.
> 
> chickenscratch figma mock:
> ![Group 128](https://github.com/actualbudget/actual/assets/22987749/93c2b650-a0c2-458c-b29a-e22c207af711)
> 
> 
> Loving the solution btw, have it hosted on Pikapod and it's really helped. Just wish I could trigger updates myself rather than waiting for Pikapod to test first but I'll take what I can get :P

Suggestion here is to create a saved filter in the all accounts page then you can apply it in just a few clicks.

**Comment by matt-fidd** [comment] 2024-06-14 10:45
For the graph to work as expected in my use case I've got to constrain it to payments and exclude deposits. Should this be a default setting?

![image](https://github.com/actualbudget/actual/assets/81489167/c5811883-adfe-4f21-950d-39f5ca418583)

Otherwise I get dips like this when I have a deposit into a category
![image](https://github.com/actualbudget/actual/assets/81489167/cb691099-743b-46e5-9b0d-dcf7590d383e)

**Comment by egelmex** [comment] 2024-06-26 14:40
For me the average view would be much more useful if it showed me min/mean/max plots for the averge period. something like this.

![graph_4_ex1](https://github.com/actualbudget/actual/assets/474014/ab2b798f-7901-41a8-b914-b30934eb8b95)

**Comment by christianmhunt** [comment] 2024-07-06 15:24
Really like this feature already. 

I would suggest adding a 'Compare this month to: This month's budget' line, (or just 'Budget'), which would compare spend against a linear series going from 0 on day 1 of the month, to the total budgeted amount for the month at the end of the month. 

Would be handy to get a rough sense of whether you were over or underspending, on average.

**Comment by Vantarc** [comment] 2024-07-08 20:30
> > Suggestion: Add option for saved/default applied filters persistent between loads/refreshes. There might be a way to do this via custom reports, but as a QOL setting OOTB for most users.
> > chickenscratch figma mock:
> > ![Group 128](https://private-user-images.githubusercontent.com/22987749/339645270-93c2b650-a0c2-458c-b29a-e22c207af711.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NzA1NjIsIm5iZiI6MTcyMDQ3MDI2MiwicGF0aCI6Ii8yMjk4Nzc0OS8zMzk2NDUyNzAtOTNjMmI2NTAtYTBjMi00NThjLWIyOWEtZTIyYzIwN2FmNzExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDIwMjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMjNkYTc1M2ViMDZjMDY2Nzc5ZGFhYmE5MzJmOWY5MWNjYThmMTdjMmU3NDg1ZmM5OWI3ZjNhOTlkM2JkMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jdXblXU0EgzMWOqy4-oKwdT0CMdcN5HGDkVncWknZFw)
> > Loving the solution btw, have it hosted on Pikapod and it's really helped. Just wish I could trigger updates myself rather than waiting for Pikapod to test first but I'll take what I can get :P
> 
> Suggestion here is to create a saved filter in the all accounts page then you can apply it in just a few clicks.

I agree, that this would be a nice workaround, but requiring the user to click on the report and then first have to apply a filter, makes the feature unusable on the report page. Otherwise I'm really loving this feature!

**Comment by jhollowe** [comment] 2024-07-16 04:45
Some positive feedback from v24.7.0: it looks and works great! I tested in Dark (my default), Midnight, and even seared my eyes to check it out in Light and the theming is readable in all.

I get that Februdary is an annoying edge case to deal with, but it would be nice to have the graph go all the way to 31 days and just have shorter months plateau at the end. Even though it is only 3 or fewer days, some expenses at the end of the month can land on these days which the graph just does not show.

**Comment by jhollowe** [comment] 2024-07-16 04:49
In addition to the previous month and running average, I would also like to be able to compate to this month a year ago. This would let me more closely compare seasonal expenses apples-to-apples rather than compare a mild June to a swealtering, AC-pumping July.

**Comment by carkom** [comment] 2024-07-16 07:10
> In addition to the previous month and running average, I would also like to be able to compare to this month a year ago. This would let me more closely compare seasonal expenses apples-to-apples rather than compare a mild June to a swealtering, AC-pumping July.

This already exists. You won't see the option if there's no data for that month last year.

**Comment by jsehnoutka** [comment] 2024-07-17 13:42
I would advocate for allowing further user customizing of the Spending Report's scope, for example allowing to exclude some categories permanently.

I know "Saved Filters" are a workaround to this but these do not apply for the dashboard overview and still take 4 clicks to apply to the report (I hope I am not doing it wrong). 

Maybe an alternative could be allowing a specific saved filter to be always applied by default to the Spending Report? That would also solve the case @matt-fidd presented and many more as that could be rather flexible.

**Comment by matt-fidd** [comment] 2024-07-17 23:49
> I would advocate for allowing further user customizing of the Spending Report's scope, for example allowing to exclude some categories permanently.
> 
> I know "Saved Filters" are a workaround to this but these do not apply for the dashboard overview and still take 4 clicks to apply to the report (I hope I am not doing it wrong).
> 
> Maybe an alternative could be allowing a specific saved filter to be always applied by default to the Spending Report? That would also solve the case @matt-fidd presented and many more as that could be rather flexible.

That would be nice, I've got a saved filter that "fixes" it but as you say it doesn't help the dashboard. I moved some money into an off budget investment and now I'm looking at this

![image](https://github.com/user-attachments/assets/68837fa3-6166-40ea-ada6-27132eaaeff9)

As opposed to the "fixed"
![image](https://github.com/user-attachments/assets/d8dc6f5f-7b6f-4211-b4bd-985d42ba0343)

**Comment by jsehnoutka** [comment] 2024-07-23 14:44
It should follow the Cash Flow report logic which is omitting transfers at the moment. I recall there was a PR for that but it did not get merged. In my Spending Report transfers to off-budget accounts are also included.

**Comment by MatissJanis** [comment] 2024-07-30 19:41
<img width="1440" alt="Screenshot 2024-07-30 at 20 34 04" src="https://github.com/user-attachments/assets/572a8bf3-3e6a-425f-ae3a-c66136e105d7">

Some feedback about the UI:

- [ ] red: I think the "save" button should be moved to the right side; this way it aligns with what the positioning of such actions with custom reports (and perhaps other reports too in the future)
- [ ] green: the spacing between these labels should be aligned to be equal; also perhaps we can make the font size smaller (see "brown" point)?
- [ ] pink: I think these options would be better to move in the header section - besides the filters; also the label should be in bold IMO
- [ ] brown: lots of dead whitespace here; if we could minimze it somehow - that would make the page look much better 

<img width="586" alt="Screenshot 2024-07-30 at 20 39 32" src="https://github.com/user-attachments/assets/ee2feeb7-34a7-45b0-996d-e8b0f4ab9d07">

- [ ] the space between active filters + the filter button is too large

---

Feature request:

Would be really nice to make "this month" a dynamic selector. I.e. "Compare "(select month)" with "(select another month)" OR "average".

**Comment by carkom** [comment] 2024-07-31 07:15
> Feature request:
> 
> Would be really nice to make "this month" a dynamic selector. I.e. "Compare "(select month)" with "(select another month)" OR "average".
> 

@MatissJanis FYI
https://github.com/actualbudget/actual/pull/3132

**Comment by carkom** [comment] 2024-07-31 10:26
> Some feedback about the UI:
> 
>     * [ ]  red: I think the "save" button should be moved to the right side; this way it aligns with what the positioning of such actions with custom reports (and perhaps other reports too in the future)
> 
>     * [ ]  green: the spacing between these labels should be aligned to be equal; also perhaps we can make the font size smaller (see "brown" point)? If we could make this legend looking closer to the cash flow graph - that would be nice
> 
>     * [ ]  pink: I think these options would be better to move in the header section - besides the filters; also the label should be in bold IMO
> 
>     * [ ]  brown: lots of dead whitespace here; if we could minimze it somehow - that would make the page look much better

Made updates in #3166. Cheers!

**Comment by matt-fidd** [comment] 2024-08-05 23:22
I think #3166 has broken the save functionality on mobile, the UI is now overlapping and you can't click the buttons any more.

![image](https://github.com/user-attachments/assets/0be69e90-75c2-44a7-a426-bea984e0e0bb)

**Comment by carkom** [comment] 2024-08-06 09:24
> I think #3166 has broken the save functionality on mobile, the UI is now overlapping and you can't click the buttons any more.
> 
> ![image](https://private-user-images.githubusercontent.com/81489167/355263255-0be69e90-75c2-44a7-a426-bea984e0e0bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5MzY0MzEsIm5iZiI6MTcyMjkzNjEzMSwicGF0aCI6Ii84MTQ4OTE2Ny8zNTUyNjMyNTUtMGJlNjllOTAtNzVjMi00NGE3LWE0MjYtYmVhOTg0ZTBlMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDA5MjIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMTgxN2M4NmRkMmI1ZWY1ZWI5ODM1M2VjMDEwNTdmZDFhNWI0NjhjNzE5NWUzZjE0NzMzZGNiNjc4ZmE5ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ttpmSUMa4SmdYumiFkF6CTHMRvOon97kxEdg57ISQgY)

Thanks for the shout. PR submitted #3209.

**Comment by andreathniah** [comment] 2024-08-08 03:24
The value for 'this month' is showing as negative instead of positive. Not sure if that is how it’s supposed to be?

![image](https://github.com/user-attachments/assets/a6c12f5e-8b18-4d87-89e9-412751582500)

**Comment by carkom** [comment] 2024-08-08 06:11
> The value for 'this month' is showing as negative instead of positive. Not sure if that is how it’s supposed to be?
> 
> ![image](https://github.com/user-attachments/assets/a6c12f5e-8b18-4d87-89e9-412751582500)
> 
> 

Only reason for that would be if you have a big deposit (credit) in one of your spending categories. 

OR your budget file has uncovered a bug that the test budget hasn't revealed.

More info is needed.

**Comment by andreathniah** [comment] 2024-08-09 11:44
> Only reason for that would be if you have a big deposit (credit) in one of your spending categories.
>
> OR your budget file has uncovered a bug that the test budget hasn't revealed.
>
> More info is needed.

Ah, I can confirm that there was a $2000 credit on 01-08-2024 (Day 1). Removing this credit results in the graph displaying as norm. Not a bug since it is as per intended design. 

![image](https://github.com/user-attachments/assets/91fa1f99-229a-4dd4-b92e-acbca0d495c9)

**Comment by matt-fidd** [comment] 2024-08-13 02:00
Potentially caused by the react aria migration

The selected saved pref no longer shows highlighted purple, but with no background and white text.

![image](https://github.com/user-attachments/assets/c47cbbfa-ea38-4829-a920-1b8ad4834041)

**Comment by nmathey** [comment] 2024-09-04 01:57
On the latest Actual release it shows next month name instead of this month one.
Data looks good from this month and previous one or calculated average though.
![image](https://github.com/user-attachments/assets/b182a71c-fe53-4d02-84b0-54bde4a8b7ce)

**Comment by MatissJanis** [comment] 2024-09-13 20:39
Feature request: legend or other visual indicator - telling you which month corresponds to which line.

<img width="1199" alt="Screenshot 2024-09-13 at 21 37 54" src="https://github.com/user-attachments/assets/9e52ec6e-76f6-4ec5-8e80-e9ea7b806c0a">

Is green line July or August? I don't know.

**Comment by matt-fidd** [comment] 2024-09-16 16:18
@carkom since #3380 I've not managed to get the dashboard widget working.

Report shows fine in the report view:
![image](https://github.com/user-attachments/assets/460aa7a6-289e-4e1e-8fc9-f59273804b6c)

But in the dashboard:
![image](https://github.com/user-attachments/assets/081bbad3-94a2-4c4b-982d-5dafa19d5ab9)

**Comment by Jonathan-Fang** [comment] 2024-09-18 07:43
I wanted to confirm that it's intentional that this spending report isn't compatible with turning on the experimental feature "customizable reports page (dashboards)?"

As in, if I turn on the dashboards feature I don't see the monthly spending report even if I have both checked but if I disable the dashboards feature I am able to access the monthly spending report.

**Comment by carkom** [comment] 2024-09-18 08:10
> I wanted to confirm that it's intentional that this spending report isn't compatible with turning on the experimental feature "customizable reports page (dashboards)?"
> 
> As in, if I turn on the dashboards feature I don't see the monthly spending report even if I have both checked but if I disable the dashboards feature I am able to access the monthly spending report.

You have to add the tile when both are enabled. Use "edit dashboard" button to add a tile.

**Comment by MatissJanis** [comment] 2024-10-09 16:50
I'm a bit late to the party, but just noticed one issue that would be great to get fixed before releasing officially:

If you create a spending report by "budget" - it uses the "budgeted" amounts. Instead I would recommend using the "balance" amounts. That's the _real_ amount of money you actually have available in the given month. (i.e. it includes rollovers from previous months)

Thoughts?

**Comment by Jonathan-Fang** [comment] 2024-10-10 04:49
If I understood you correctly, why not have a way to create a spending report by "budget" and another way by "balance?"

I wouldn't want to confuse by clicking budget, and then I get balance.

**Comment by joel-rich** [comment] 2024-10-11 20:46
I've discovered a strange bug where the Monthly Spending report appears to not include some transactions at the end of the month when there is a deposit.

I set up the "For budget" transaction list; filtering to a single month and excluding income categories to be able to check the "Filtered balance" total against the Monthly Spending report totals. If there are no deposits on the 30th or 31st, the totals match.

Based on a bunch of trial an error, it looks like the Monthly Spending report excludes transactions based on whether there is a deposit on the 30th or 31st. 
- If a deposit is on the 30th, all transactions from the 30th and 31st are excluded. 
- If a deposit is on the 31st, all transactions on the 31st are excluded. 
- If the last deposit of the month is on the 29th or earlier, everything works properly and all transactions from the 30th and 31st are counted.

**Closed** 2024-10-23 05:59 UTC
Labels: feedback

**Comment by MatissJanis** [comment] 2024-10-23 17:21
The feature has now been merged as a first-party feature. If there is any additional feedback and/or bug reports - please open separate issues.

Also if you feel like your comment in here wasn't addressed (and should have been) - please do open a separate issue.

Conversations here have been locked.
