### ISSUE TITLE
[Bug]: OFX Importer "Corrupts" Existing Entries

### ISSUE THREAD

**Issue by Silvenga** [actualbudget/actual#1081] opened 2023-05-31 18:31 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

So there was this bug in non-OSS Actual where importing a OFX file would override existing entries incorrectly. This was reproducible with a clean database and a copy of the OFX files. Maybe @jlongster remembers?

For example, say the following was entered:

```
5/28/2023 Torchy's Tacos
```

After importing, the following would be shown:

```
5/28/2023 Torchy's Tacos (new)
5/28/2023 Torchy's Tacos
```

But in reality, the old entry was internally linked with a transaction id of Jamba Juice (but the entry wasn't updated for Jamba Juice). From the UI, it looks like transactions were duplicated, but in reality, old transactions were incorrectly updated. 

## Old Solution (No longer works)

I was using the tool tips to figure out when this corruption happened, but they were removed in https://github.com/actualbudget/actual/issues/567.

Previously, I would use the tool tips to see if this corruption occurred and remove the offending entries (to perform a clean import).

## Other Notes

This only happens with Citi Bank (I have multiple cards with them).

### What error did you receive?

No errors.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by Silvenga** [comment] 2023-05-31 18:33
Would it be possible to enable tooltips again, just to aid in tracking down this issue. My worry, there's no error, so it could silently break a database's ids (without understanding how this could happen).

**Comment by Silvenga** [comment] 2023-05-31 22:26
Unfortunately, the repo-case was uploaded to the Slack instance, but has since been deleted (free version of Slack).

I'll try and find a new one (took a couple months last time).

**Comment by Shazib** [comment] 2023-06-17 00:17
@Silvenga I think as a temporary workaround you can see the guid in dev tools, e.g. Firefox: 

![image](https://github.com/actualbudget/actual/assets/4405777/263dd5b6-310b-4ead-9c37-86de3eaf7b1c)

**Comment by MatissJanis** [comment] 2023-08-26 14:20
👋 Would you be able to provide reproduction steps and/or demo budget?

Without having reproduction I don't think anyone will be able to asist.

**Comment by Silvenga** [comment] 2023-08-26 17:38
@MatissJanis it's rather hard since I don't have access to the transaction id anymore, after the tooltip was removed. The workaround proposed by @Shazib doesn't work since that focus id isn't the transaction id that was originally specified in the old tooltip.

**Comment by Silvenga** [comment] 2023-08-26 17:39
(part of the problem is that I can't upload my whole database to github - making creating a repo exponentially harder)

**Comment by MatissJanis** [comment] 2024-03-03 21:45
Closing due to missing reproduction steps.

**Closed by MatissJanis** 2024-03-03 21:45 UTC
Labels: bug, needs info, transaction import
