### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ArmandoAmmar** [actualbudget/actual#3978] opened 2024-12-13 11:23 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When I click to create a rule, then I select "import payee" and click on "contains" a red message appears saying to me to create a issue into github because something goes worng internally. Then all my payees disapear and I need to restart actual.

### Where are you hosting Actual?

Desktop App (Electron)

### Operating System

Windows 10

**Comment by Teprifer** [comment] 2024-12-13 11:37
Couldn't reproduce the payees disappearing bit, and I could continue editing the rule.

Looks like this was also fixed by #3943  as I can't reproduce it there. Can you confirm? Try the deploy preview link.

**Comment by coda538** [comment] 2024-12-14 18:11
Same issue for me. Workaround thanks to @Teprifer : 
- create a new rule "Notes is (nothing)"
- modify "Notes is something"
- modify "Notes contains something"
and it works!

**Comment by matt-fidd** [comment] 2024-12-15 17:18
This is fixed in edge by #3943 and will be fixed in v25.1

**Closed by matt-fidd** 2024-12-15 17:18 UTC
Labels: bug

**Comment by ArmandoAmmar** [comment] 2024-12-15 17:27
Thanks
