### ISSUE TITLE
[Bug]: Importing Quicken file shows spinning wheel and "Something internally went wrong" [23.9.0]

### ISSUE THREAD

**Issue by bverkron** [actualbudget/actual#1730] opened 2023-09-23 23:22 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When attempting to import the attached Quicken file (qfx) the import dialog just shows a spinning wheel and an error in the bottom right shows "Something internally went wrong". See attached images. Other formats for this account / institution like .ofx (Microsoft Money according to the download option) work fine. I tried Safari Version 16.5.2 and Brave v1.58.129

**[sample.qfx.zip](https://github.com/actualbudget/actual/files/12707441/sample.qfx.zip)**

This worked fine in release 23.8.1 last time I used it (pretty sure that's the version I was running just before upgrading to 23.9.0)

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/19174503/50b1accb-2cee-42f0-aaac-ad9951db320e)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by bverkron** [comment] 2023-09-24 00:34
This just happened with a .qfx file from another institution too.

**Comment by MatissJanis** [comment] 2023-09-24 16:42
Duplicate of https://github.com/actualbudget/actual/issues/1653#issue-1880849119

**Closed by MatissJanis** 2023-09-24 16:42 UTC
Labels: bug

**Comment by bverkron** [comment] 2023-09-24 16:54
> Duplicate of [#1653 (comment)](https://github.com/actualbudget/actual/issues/1653#issue-1880849119)

My apologies. That issue did not come up in my searches for some reason.
