### ISSUE TITLE
[Bug]: Unable to download my finances

### ISSUE THREAD

**Issue by ribab** [actualbudget/actual#2882] opened 2024-06-15 02:04 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

![image](https://github.com/actualbudget/actual/assets/3980777/154eb47a-40b9-40d1-bd65-a15a6a522ab2)

I'm seeing this error. I think it happened when I clicked "add" to add a new transaction, but then pressed cancel. After that nothing in the app would load, and when I refreshed I couldn't get back into my finances.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by MatissJanis** [comment] 2024-06-16 13:51
👋 Hi! I can see how this issue can be very frustrating for you. But sadly there isn't much we can do to help without more debug information (and possibly a way to reproduce).

Would you mind reaching out to the community on discord with tech support with this issue? Folks there are pretty active and eager to help out. They should be able to better diagnose the root-cause. At which point we could see if there's any work we could do to patch things up.

**Comment by MatissJanis** [comment] 2024-07-08 18:49
👋 Closing due to lack of information.

**Closed by MatissJanis** 2024-07-08 18:49 UTC
Labels: bug, needs info
