### ISSUE TITLE
[Bug]: Import of data with long numbers such as -0.30000000000000004 messes the server and we see internal error in multiple places.

### ISSUE THREAD

**Issue by yeluripati-ha** [actualbudget/actual#2457] opened 2024-03-12 12:12 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [X] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

If an imported file/data includes numbers with a long decimal, the server does not seem to be able to handle it. When you scroll the list of transactions to the errant transaction, the server throws an error and needs to be restarted. This cannot be fixed, there is no way to view the transaction so it can be deleted. Restarting the server does not help. I am not able to close the account/delete it, I get an internal error, other screens (like Custom Reports) display internal error after this. My only option is to close and delete the entire file and restart again.

Client version: v24.3.0
Server version: v24.3.0

### What error did you receive?

This is the error in the client side browser:

Error: safeNumber: can’t safely perform arithmetic with number: 3000000000000000500 at N_ (https://192.168.25.175:5006/static/js/index.O6ABAWXP.js:58:92092) at _n (https://192.168.25.175:5006/static/js/index.O6ABAWXP.js:58:92257) at wt (https://192.168.25.175:5006/static/js/wide.Puo4nQYF.chunk.js:1:56913) at https://192.168.25.175:5006/static/js/wide.Puo4nQYF.chunk.js:1:64250 at Object.Ak [as useState] (https://192.168.25.175:5006/static/js/index.O6ABAWXP.js:56:22457) at Ee.useState (https://192.168.25.175:5006/static/js/index.O6ABAWXP.js:9:6382) at https://192.168.25.175:5006/static/js/wide.Puo4nQYF.chunk.js:1:64237 at J1 (https://192.168.25.175:5006/static/js/index.O6ABAWXP.js:56:19539) at yv (https://192.168.25.175:5006/static/js/index.O6ABAWXP.js:58:3139) at bD (https://192.168.25.175:5006/static/js/index.O6ABAWXP.js:58:2351)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by youngcw** [comment] 2024-03-12 14:23
in the short term you could try to find the value in the db file and fix it there.

**Comment by slimslickner** [comment] 2024-03-19 12:08
I recreated this same issue a while back. I got to this point by aggregating a split transaction with pandas from a Quicken export to then import to Actual.

**Comment by MatissJanis** [comment] 2024-03-21 18:32
👋 Would you mind providing an example file to reproduce the issue? Without a clear reproduction path it will be very difficult to assist in fixing this.

**Comment by MatissJanis** [comment] 2024-03-23 09:48
Actually.. this is a duplicate of https://github.com/actualbudget/actual/issues/1811. And since we have reproduction steps in 1811 - I'll close this one.

**Closed by MatissJanis** 2024-03-23 09:48 UTC
Labels: bug, needs info
