### ISSUE TITLE
[Bug]: Nordigen fails to parse transactions from SEB Card bank (SEB_KORT_AB_SE_SKHSFI21)

### ISSUE THREAD

**Issue by leikoilja** [actualbudget/actual#761] opened 2023-03-16 14:43 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Bank id SEB_KORT_AB_SE_SKHSFI21 from [data points](https://docs.google.com/spreadsheets/d/1ogpzydzotOltbssrc3IQ8rhBLlIZbQgm5QCiiNJrkyA/edit#gid=489769432)

Transaction log from server logs:
```js
{
      transactionId: '202303140202946',
      bookingDate: '2023-03-14',
      valueDate: '2023-03-13',
      transactionAmount: { amount: '31.95', currency: 'SEK' },
      additionalInformation: 'COOP VÄSTRA SKOGEN',
      proprietaryBankTransactionCode: 'PURCHASE',
      internalTransactionId: '5b8e5fbb174435f61d0cf3e2d94aec76',
    }
```
And the ActualBudget parsed transaction:
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/10655107/225650982-bbb6fc96-b30e-4073-b561-7d29b80ce86a.png">

Few issues i see here:
1. No payee/notes are parsed. Since the only meaningful data pulled is in `additionalInformation`, i'd probably expect that should go under `notes` and `payee` will have to be manually assigned per transaction
2. Transaction in the actualbudget is categorized as `deposit`, which is incorrect and must be `payment`

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by Jackenmen** [comment] 2023-03-16 15:00
> 2\. Transaction in the actualbudget is categorized as `deposit`, which is incorrect and must be `payment`

For a transaction to be categorized as payment, its amount needs to be negative. It sounds like this could be an upstream issue with Nordigen for this bank. Would you mind contacting them about this here? (select "Insufficient, missing or duplicated data and data quality feedback" in the "Issue" dropdown list)

https://nordigen.zendesk.com/hc/en-gb/requests/new?ticket_form_id=6775215268637

> 1. No payee/notes are parsed. Since the only meaningful data pulled is in `additionalInformation`, i'd probably expect that should go under `notes` and `payee` will have to be manually assigned per transaction

Yeah, if `additionalInformation` is used for transaction description then it may make sense to add a custom integration for this bank as I don't think that this field typically contains "notes"-worthy information (though I must say I haven't seen this field much at all). I do wonder if the lack of `creditor/debtorAccount` and `creditor/debtorName` is something that Nordigen could improve but that depends on what data they get. It might make sense to ask them just in case it's just another issue with their integration though I think it's likely that they simply don't get this information from that bank.

**Comment by leikoilja** [comment] 2023-03-17 09:22
Update, got this email from Nordigen team
![image](https://user-images.githubusercontent.com/10655107/225864439-686213ca-320f-4427-8ac0-99f9238e2d96.png)

WIll keep this issue posted on any updates/fixes

**Comment by MatissJanis** [comment] 2023-04-23 20:42
👋 I'll close this off since the issue is on Nordigen to fix and not Actualbudget. But if you get an update: please post it in the comments.

**Closed by MatissJanis** 2023-04-23 20:42 UTC
Labels: bug, bank sync, sync: nordigen
