### ISSUE TITLE
[Bug]: Shortcut "N" for Notes fills the Note with an "n"

### ISSUE THREAD

**Issue by nicedevil007** [actualbudget/actual#2687] opened 2024-04-30 07:36 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

A bug happened!

If I select multiple Transactions and then hit the shortcut "N" it leads to a popup for the new note that already contains the letter "n" from pressing the shortcut.

![image](https://github.com/actualbudget/actual/assets/17103076/bc77c802-6e92-4779-840d-225991b7c768)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by Jenna59** [comment] 2024-04-30 15:34
I can take a look.

**Comment by shall0pass** [comment] 2024-04-30 15:59
This is a duplicate of https://github.com/actualbudget/actual/issues/2662
The issue isn't present on the Master branch and will be resolved with the next release.

**Closed by shall0pass** 2024-04-30 15:59 UTC
Labels: bug
