### ISSUE TITLE
[Bug]: Search Function for Category does not work

### ISSUE THREAD

**Issue by Crazypkr1099** [actualbudget/actual#2323] opened 2024-02-03 15:35 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [X] I have checked my server logs and could not see any errors there
- [ ] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [X] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

When typing in the category name into the search, it does not show the sub categories, making it very difficult to find a subcategory. For example, if the category is "food" , you should be able to type "food" into the search and have the subcategories "groceries, dining out", etc. show up.

![bug2](https://github.com/actualbudget/actual/assets/11566471/2591aee5-f48d-4f70-a276-a892f88467d9)
![bug1](https://github.com/actualbudget/actual/assets/11566471/5f469ae4-fda6-4b04-823b-2bc13d5e552d)

### What error did you receive?

No error, just no results.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by MatissJanis** [comment] 2024-02-03 15:40
Duplicate of https://github.com/actualbudget/actual/issues/1615

We've been back-and-forth with this for a while now and the current consensus is that category groups should not be included in search results.

**Closed by MatissJanis** 2024-02-03 15:40 UTC
Labels: bug
