### ISSUE TITLE
[Bug]: Split transactions are double counted in off-budget accounts, if split is done after transaction is created

### ISSUE THREAD

**Issue by andresponte** [actualbudget/actual#1810] opened 2023-10-17 18:50 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When an **existing transfer** to an off-budget account is converted from a "normal" category to split category, the split transactions are double counted in the off-budget account

**Before**:
![imagen](https://github.com/actualbudget/actual/assets/69403695/7f7b6c49-7071-49fd-963f-9782199be7eb)
**After**:
![imagen](https://github.com/actualbudget/actual/assets/69403695/be0d548e-6a54-444d-b5c6-de06389ece96)
![imagen](https://github.com/actualbudget/actual/assets/69403695/8b847ffb-eac1-483e-ab07-8c514671770a)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by lephtHanded** [comment] 2023-10-18 02:49
i just came here to post this same issue.

**Comment by joel-jeremy** [comment] 2023-10-19 04:18
Hi 👋 Thank you for reporting the issue! This is a duplicate of https://github.com/actualbudget/actual/issues/1746 and should already been fixed in the edge version and will be included in the next release.

**Comment by joel-jeremy** [comment] 2023-10-20 23:59
Closing this as duplicate

**Closed by joel-jeremy** 2023-10-20 23:59 UTC
Labels: bug
