### ISSUE TITLE
[Bug]: SimpleFin Authentication Reset

### ISSUE THREAD

**Issue by RandomSwiss7983242** [actualbudget/actual#2516] opened 2024-03-29 16:12 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [X] I will be attaching my server logs to this issue
- [X] I will be attaching my client-side (browser) logs to this issue
- [X] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

I think I found a bug relating to the simplefin authentication. I had an unrelated issue and I ended up deleting my simplefin API key and creating a new one. After a relogin to actualbudget I went to go add a new account with simplefin. The GUI shows an error Something internally went wrong. You may want to restart the app if anything looks wrong. `Please report this as a new issue on Github.` and the docker logs show the below.

```
58fac0e8600f SyntaxError: Unexpected token < in JSON at position 0
58fac0e8600f     at JSON.parse (<anonymous>)
58fac0e8600f     at IncomingMessage.<anonymous> (file:///app/src/app-simplefin/app-simplefin.js:237:24)
58fac0e8600f     at IncomingMessage.emit (node:events:529:35)
58fac0e8600f     at endReadableNT (node:internal/streams/readable:1400:12)
58fac0e8600f     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
From the GUI, the loading icon just spins, but I'm not ever able to update/fix my simplefin API key.

Is there anyway to update/fix the simplefin API key manually in a sqlite backup?

I believe I found a workaround. I created a backup of my existing budget. I stopped the container and created a tar.gz of the `/data` directory. I then started the container. From the Web UI, I recreated a password. Then, I followed the [restore procedures](https://actualbudget.org/docs/backup-restore/restore/) to reload my previously created backup.

I re-enabled the experimental feature for simplefin. I went back to the `add account` and was able to enter my updated API key.

### What error did you receive?

See `What happend?` for the error message

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mac OSX

**Comment by youngcw** [comment] 2024-04-04 15:10
It is known that the bank sync needs a way to update the keys.  I believe that has already been brought up in the simplefin feedback issue.  Ill close this as being a duplicate of that

**Closed by youngcw** 2024-04-04 15:10 UTC
Labels: bug, bank sync
