### ISSUE TITLE
[Bug]: Docker image stuck on "closing screen"

### ISSUE THREAD

**Issue by fref** [actualbudget/actual#2469] opened 2024-03-16 16:01 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### Is this related to GoCardless, Simplefin or another bank-sync provider?

- [ ] I have checked my server logs and could not see any errors there
- [X] I will be attaching my server logs to this issue
- [ ] I will be attaching my client-side (browser) logs to this issue
- [ ] I understand that this issue will be automatically closed if insufficient information is provided

### What happened?

I imported a YNAB4 budget into a brand new docker image (latest-alpine).
Import was successful (as far as I can tell from a quick glance at the contents). I tried to close the file to import my second budget, but the interaction is stuck with this display:
![image](https://github.com/actualbudget/actual/assets/130824/b76ef3e8-7e31-47a0-b60c-47fff7660a52)

### What error did you receive?

Looking at the docker logs, I can see:
```
Rejection: SqliteError: no such table: messages_binary
    at Database.prepare (/app/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at WrappedDatabase.all (file:///app/src/db.js:13:24)
    at Module.sync (file:///app/src/sync-simple.js:74:24)
    at file:///app/src/app-sync.js:111:42
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/app/node_modules/express/lib/router/index.js:346:12) {
  code: 'SQLITE_ERROR'
}
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by MatissJanis** [comment] 2024-03-21 18:31
👋 Would you mind providing steps how to reproduce this with an example YNAB4 export? We won't be able to assist much without having a way to reproduce the issue.

**Comment by fref** [comment] 2024-03-25 09:25
I'll try to prepare that without personal info

**Comment by MatissJanis** [comment] 2024-04-13 18:51
Closing due to lack of information.

**Closed by MatissJanis** 2024-04-13 18:51 UTC
Labels: bug, needs info
