### ISSUE TITLE
Account Selector Showing Closed Account & Repeating Rows

### ISSUE THREAD

**Issue by koonspace** [actualbudget/actual#290] opened 2021-11-16 09:13 UTC
Hi James,

Love your work, have just migrated from nYNAB with 5 years worth of transactions.

I'm having an issue where closed accounts are shown in the account selector when adding a new transaction, and 'Off Budget' and 'For Budget' headings are shown multiple times as shown below.

Is this a bug or did I do something wrong? Thanks!

<img width="221" alt="Screen Shot 2021-11-16 at 22 09 44" src="https://user-images.githubusercontent.com/93066665/141956356-c0bb4e40-ea13-4021-8374-25321bcd83ea.png">

**Comment by rich-howell** [comment] 2022-10-18 16:34
This is re-producable 

![image](https://user-images.githubusercontent.com/22135084/196490041-e97fcaf4-6bf0-4ad4-9105-22a24be6c2ab.png)
![image](https://user-images.githubusercontent.com/22135084/196490156-98ec652f-c5c5-4126-a678-ae6aca17803d.png)

**Comment by gsumpster** [comment] 2023-02-04 19:09
Tested this locally, this seems to be fixed, I think we can close this one out!

<img width="709" alt="CleanShot 2023-02-04 at 11 08 48@2x" src="https://user-images.githubusercontent.com/3413011/216785300-d62b6f94-064a-4092-bb3c-8f2923af5597.png">

**Comment by j-f1** [comment] 2023-02-04 20:06
@rich-howell Can you verify? since you reproduced it earlier.

**Comment by MatissJanis** [comment] 2023-03-30 19:06
👋 Closing it off. I also think this has been addressed.

**Closed by MatissJanis** 2023-03-30 19:06 UTC
Labels: bug, user interface
