### ISSUE TITLE
[Feature] Can we get an installments condition on  rules?

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#520] opened 2023-01-22 18:34 UTC
### Discussed in https://github.com/actualbudget/actual/discussions/241

<div type='discussions-op-text'>

<sup>Originally posted by **manuelcanepa** September  2, 2022</sup>
I would like to set installments on schedule to be easy set a new future charge on my card. I have an credit card account and there i schedule every recurrency payment, but in some cases that recurrency has an end. It is possible or is just a too personal improvement?</div>

**Comment by MatissJanis** [comment] 2023-01-25 18:10
Closing this as a duplicate of: https://github.com/actualbudget/actual/issues/308

Once we get this ticket solved, you should be able to do what was wanted :)

**Closed by MatissJanis** 2023-01-25 18:10 UTC
Labels: needs triage, rules, feature
