### ISSUE TITLE
[Bug]: Spending report crashes

### ISSUE THREAD

**Issue by sbc64** [actualbudget/actual#2122] opened 2023-12-23 03:19 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I have an ecnrypted database, which I don't think it matters. On version 3.10 the Spending Report used to work. Since version 3.11 and 3.12 the Spending Report is not working and I get greated with the crash screen:

<img width="609" alt="Screenshot 2023-12-22 at 21 15 37" src="https://github.com/actualbudget/actual/assets/10123236/1e9e2b36-b335-4efb-af55-bc1d633c2b9a">

### What error did you receive?

Error from within the Actual app:
```
tk@https://<url>/static/js/reports.dec86016.chunk.js:1:39472
i2@https://<url>/static/js/main.39d3269d.js:37:64289
lB@https://<url>/static/js/main.39d3269d.js:37:117584
lI@https://<url>/static/js/main.39d3269d.js:37:113204
lE@https://<url>/static/js/main.39d3269d.js:37:113132
lT@https://<url>/static/js/main.39d3269d.js:37:112984
lp@https://<url>/static/js/main.39d3269d.js:37:109296
lh@https://<url>/static/js/main.39d3269d.js:37:108248
k@https://<url>v/static/js/main.39d3269d.js:96:1548
M@https://<url>/static/js/main.39d3269d.js:96:1911 
```

Error from the console of the browser (Firefox):

```
TypeError: can't access property "every", t is undefined
    tk CategorySelector.tsx:38
    React 7
        i2
        lB
        lI
        lE
        lT
        lp
        lh
    k scheduler.production.min.js:13
    M scheduler.production.min.js:14
[react-dom.production.min.js:189:29](<url>/node_modules/react-dom/cjs/react-dom.production.min.js)
    React 9
        aZ
        callback
        im
        sL
        sN
        sz
        lP
        lD
        lh
    k scheduler.production.min.js:13
    M scheduler.production.min.js:14
 ```
 
 P.S. If you want me to do local development on the app I can try to do it. I'm just reporting the issue I'm seeing with the app. Thank you very much for this wonderful software you are building. ❤️

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment] 2023-12-23 03:31
Have yout tested demo.actualbudget.org?  I believe this issue has been fixed and will be in that web demo.

**Comment by MatissJanis** [comment] 2023-12-23 10:08
Duplicate of https://github.com/actualbudget/actual/issues/1981

**Closed by MatissJanis** 2023-12-23 10:08 UTC
Labels: bug
