### ISSUE TITLE
[Bug]: Custom reports average spending spread across months with no transactions

### ISSUE THREAD

**Issue by rockoo** [actualbudget/actual#3065] opened 2024-07-16 15:28 UTC
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When using custom reports for a specific category the "average spending" interval is spread across months selected even when there are no transactions for those months.

**Steps to reproduce:**
1. go to custom reports
2. choose a category
3. click to show summary
4. choose range (include months that have no transactions)

**Expected**
Show the average based on actual transactions

**Actual**
the average spending is calculated across the range even when the months have no transactions. i.e. if i choose 4 months with $2000 in transactions but those $2000 is only in the last two months the average will be caluclated as AMOUNT / MONTHS (or interval chosen). This is misleading and not actual spending

### Where are you hosting Actual?

Docker

### Operating System

Linux

**Comment by carkom** [comment] 2024-07-22 12:44
I see your point. However there is a counter-point to consider. If I usually spend $100 a month in a category over the course of 6 months but for two of those months I spend $0, I'd consider my average spending over that 6 month period to be $400 / 6 months or $66.66 per month. 

In your case you're measuring this scenario as $100 per non-zero month or $100 per month (only counting months where something was spent).

I think the current equation is much more understandable for the average (non-math oreiented) individual.

**Comment by carkom** [comment] 2024-07-22 12:52
Another way to look at it: If you get paid $2000 every other week and you were asked "how much do you get paid weekly" would you say "I get paid $2000 per non-zero week and I'm paid every other week" or would you say "I get paid $1000 per week" or maybe you'd say "I don't get paid weekly, I get paid $2000 every other week". 

No matter how you answer the above question, we are creating a software to work for a wide range of people. Some people spend every month some spend in fits and spurts and may not use a category for a couple months at all but ultimately we need a metric that can work for the largest group of people possible and be as simple and understandable as possible.

I hope this helps, let me know if you have other questions. I'm closing this as the metric is working as intended.

**Closed by carkom** 2024-07-22 12:52 UTC
Labels: bug
